services:
  db:
    image: postgres:16
    env_file:
      - backend/.env.docker
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    profiles: ["backend"] # Enable with: docker compose --profile backend up --build backend
    build: ./backend
    env_file:
      - backend/.env.docker
    depends_on:
      - db
    ports:
      - "8000:8000"

volumes:
  db-data:

# postgres only: docker compose up db --build
# backend and postgres: docker compose --profile backend up --build db backend
