/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/validate-trip-input": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate Trip Input
         * @description Validate a trip input (origin or destination).
         *
         *     Returns corrected values if the input was valid but had typos/formatting issues.
         *     For destinations, may return multiple values if the input contained multiple
         *     places (e.g., "Paris and Rome" -> ["Paris", "Rome"]).
         *
         *     Raises HTTP 503 if validation fails after retries.
         *
         *     Tier 11.1: Uses async validation with non-blocking retries for better concurrency.
         */
        post: operations["validate_trip_input_api_validate_trip_input_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/destination-image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get Destination Image
         * @description Get the Unsplash image URL for a destination.
         *
         *     Called when user selects a destination to show the correct banner image
         *     immediately, without waiting for plan generation.
         */
        post: operations["get_destination_image_api_destination_image_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/clear-validation-cache": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Admin Clear Validation Cache
         * @description Clear the validation cache. For development/debugging only.
         */
        post: operations["admin_clear_validation_cache_api_admin_clear_validation_cache_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/fresh-start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Admin Fresh Start
         * @description Perform a complete system cache and checkpoint cleanup.
         *
         *     This clears:
         *     - All validation caches (preserving rate limiting)
         *     - All LLM response caches
         *     - All stale LangGraph checkpoints (>24h idle)
         *
         *     For development/debugging and maintenance only.
         *     Does NOT clear rate limiting cache to prevent abuse.
         */
        post: operations["admin_fresh_start_api_admin_fresh_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/graph-stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Admin Graph Stats
         * @description Get comprehensive graph statistics for observability.
         *
         *     Returns routing decisions, template usage, and cache performance metrics.
         *     Useful for monitoring token savings and optimization effectiveness.
         *
         *     Response:
         *     {
         *         "routing": {
         *             "keyword_bypasses": int,  # Router skipped via keyword heuristic
         *             "router_calls": int,      # Router LLM was invoked
         *             "negation_defers": int,   # Keyword was negated, deferred to router
         *             "keyword_bypass_rate": float
         *         },
         *         "templates": {
         *             "template_hits": int,    # Template found and used
         *             "template_misses": int,  # No template, fell back to LLM
         *             "template_hit_rate": float
         *         },
         *         "extractor_cache": {...},
         *         "strategy_cache": {...}
         *     }
         */
        get: operations["admin_graph_stats_api_admin_graph_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/planner": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Admin Planner Debug
         * @description Get planner configuration and build identifiers for ops debugging.
         *
         *     Returns stable JSON schema with behavioral config and build info.
         *     Useful for verifying deployment state and debugging cache issues.
         *
         *     Response includes:
         *     - admin_endpoint_version: Schema version for evolution tracking
         *     - prompt_bundle_hash: Hash of prompt templates
         *     - planner_build_id: Git SHA or build ID
         *     - cache_schema_version: Cache payload schema version
         *     - enabled_strategy_topics: List of enabled strategy topics
         *     - enabled_strategy_topics_source: "defaults" or "env_override"
         *     - enable_all_strategy_topics: Whether env override is active
         *     - llm_budget_max_calls_non_ready: Max LLM calls per non-ready turn
         *     - cache_ttl_map_seconds: TTL per cache type
         *     - gate_precedence_version: Gate logic version
         *     - node_logic_version: Per-node logic versions
         *     - strategy_output_caps: Max output characters for strategy responses
         */
        get: operations["admin_planner_debug_api_admin_planner_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/clear-all-checkpoints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Admin Clear All Checkpoints
         * @description Clear ALL LangGraph checkpoints regardless of age.
         *
         *     Use with caution - this will clear all in-progress session states.
         *     For emergency maintenance only.
         */
        post: operations["admin_clear_all_checkpoints_api_admin_clear_all_checkpoints_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/clear-all-caches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Admin Clear All Caches
         * @description Clear ALL caches in the system - comprehensive cache reset.
         *
         *     Clears:
         *     - All LangGraph/planner caches (Response, Extractor, Strategy, Tile, GateEvaluation)
         *     - All validation caches (including rate limiting)
         *     - Unsplash memory cache
         *     - Unsplash database cache
         *     - All LangGraph checkpoints
         *     - Prompt/template caches
         *
         *     WARNING: Destructive operation for development/maintenance only.
         */
        post: operations["admin_clear_all_caches_api_admin_clear_all_caches_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/specialist-cache-stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Admin Specialist Cache Stats
         * @description Get specialist LLM cache statistics for observability.
         *
         *     Returns L1 (memory) and L2 (database) hit/miss counts, sizes, and TTLs.
         */
        get: operations["admin_specialist_cache_stats_api_admin_specialist_cache_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/clear-specialist-cache": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Admin Clear Specialist Cache
         * @description Clear both L1 (memory) and L2 (database) specialist caches.
         *
         *     Use for development/debugging when you want fresh LLM calls.
         */
        post: operations["admin_clear_specialist_cache_api_admin_clear_specialist_cache_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/tile-cache-stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Admin Tile Cache Stats
         * @description Get tile data cache statistics for observability.
         *
         *     Returns L1 (memory) and L2 (database) hit/miss counts, sizes, and TTLs.
         */
        get: operations["admin_tile_cache_stats_api_admin_tile_cache_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/clear-tile-cache": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Admin Clear Tile Cache
         * @description Clear both L1 (memory) and L2 (database) tile caches.
         *
         *     Use for development/debugging when you want fresh provider data.
         */
        post: operations["admin_clear_tile_cache_api_admin_clear_tile_cache_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/router-cache-stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Admin Router Cache Stats
         * @description Get router extraction cache statistics for observability.
         *
         *     Note: Router cache is L1-only (no database persistence).
         *     Shows hits, misses, and skipped context-dependent queries.
         */
        get: operations["admin_router_cache_stats_api_admin_router_cache_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/clear-router-cache": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Admin Clear Router Cache
         * @description Clear router extraction cache (L1 memory only).
         *
         *     Use for development/debugging when you want fresh extractions.
         */
        post: operations["admin_clear_router_cache_api_admin_clear_router_cache_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/cache-stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Admin All Cache Stats
         * @description Get all cache statistics in one call.
         *
         *     Returns stats for:
         *     - Specialist cache (L1 + L2)
         *     - Tile cache (L1 + L2)
         *     - Router cache (L1 only)
         */
        get: operations["admin_all_cache_stats_api_admin_cache_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tiles/click": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Track Tile Click
         * @description Persist a tile click for analytics.
         */
        post: operations["track_tile_click_api_tiles_click_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/suggestions/click": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Track Suggestion Click
         * @description Persist a suggestion pill click for analytics.
         *     Tracks which LLM-generated suggestions users find valuable.
         */
        post: operations["track_suggestion_click_api_suggestions_click_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graph_plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Graph Plan Endpoint
         * @description LangGraph-based planning endpoint.
         *
         *     Accepts a user message and optional session state, runs the graph planner,
         *     persists document updates, and returns the updated session state.
         *
         *     Features:
         *     - Feature flag gating (ENABLE_GRAPH_PLAN_ROUTE)
         *     - Payload size validation
         *     - Optimistic concurrency via document versioning
         *     - Cache-Control: no-store to prevent caching of personalized responses
         */
        post: operations["graph_plan_endpoint_api_graph_plan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graph_plan/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Graph Plan Stream Endpoint
         * @description Streaming version of the graph plan endpoint using Server-Sent Events (SSE).
         *
         *     Streams tokens as they are generated, then sends a final 'complete' event
         *     with the full response data including session state and extracted trip inputs.
         *
         *     SSE Event Format:
         *         event: token
         *         data: {"type": "token", "data": "..."}
         *
         *         event: complete
         *         data: {"type": "complete", "data": {...}}
         *
         *         event: error
         *         data: {"type": "error", "message": "..."}
         */
        post: operations["graph_plan_stream_endpoint_api_graph_plan_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Reset Session
         * @description Reset/delete a planning session and all associated data.
         *
         *     Uses row-level locking to prevent deadlocks with concurrent plan operations.
         *     Also clears session cookies from the browser and LangGraph checkpoint state.
         */
        delete: operations["reset_session_api_session_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Chat History
         * @description Get chat history for the current session.
         *
         *     Returns the last 50 messages in chronological order (oldest first).
         *     Used by the frontend to restore chat state on page load.
         */
        get: operations["get_chat_history_api_chat_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/last": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Last Message
         * @description Delete the last user message and its associated assistant response.
         *
         *     This operation:
         *     1. Finds the most recent user message
         *     2. Retrieves the trip_inputs snapshot from that message (if available)
         *     3. Deletes the user message and all subsequent messages
         *     4. Restores trip_inputs from the snapshot (if available)
         *     5. Returns the deleted count, restored trip_inputs, and remaining messages
         *
         *     Used for "undo" functionality to revert the last chat turn.
         */
        delete: operations["delete_last_message_api_chat_last_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/document": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Plan Document
         * @description Get the current plan document for a session.
         *     Returns the centralized source of truth for branches and tiles.
         */
        get: operations["get_plan_document_api_document_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Plan Document
         * @description Apply a partial update to the plan document.
         *     Uses CRDT-style merge: additions win, deletions require explicit flags.
         */
        patch: operations["patch_plan_document_api_document_patch"];
        trace?: never;
    };
    "/api/document/tiles/{branch_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Fetch Tiles For Branch
         * @description Fetch tiles for a specific branch and add them to the document.
         *     Used when switching branches to load tiles on demand.
         */
        post: operations["fetch_tiles_for_branch_api_document_tiles__branch_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tiles/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Tiles
         * @description Force refresh tiles for a branch with current settings.
         *
         *     Use this endpoint when user preferences (hotel_settings, flight_settings,
         *     activity_settings) change to get updated tiles reflecting the new filters.
         *
         *     The cache key includes settings hashes, so changing settings will trigger
         *     a cache miss and fresh fetch.
         */
        post: operations["refresh_tiles_api_tiles_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/document/fill-day": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Fill Day Endpoint
         * @description Fill a free day with activity tiles. No LangGraph execution.
         */
        post: operations["fill_day_endpoint_api_document_fill_day_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/expand-itinerary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Expand Itinerary Endpoint
         * @description Expand strategy into full itinerary (Stage 2 -> Stage 3).
         *
         *     Streams NDJSON events:
         *         {"type": "progress", "stage": "itinerary", "message": "...", "pct": 30}
         *         {"type": "envelope", "plan_envelope": {...}}
         *         {"type": "done", "plan_view_state": "S3_ITINERARY_READY|S3_EDITING|S3_PARTIAL_CONFLICT"}
         *         {"type": "error", "message": "..."}
         *
         *     NOTE: This endpoint does NOT use FastAPI's db dependency injection because
         *     StreamingResponse generators run AFTER the endpoint returns, at which point
         *     the injected session is closed. Instead, we create a fresh session inside
         *     the generator using the session factory.
         */
        post: operations["expand_itinerary_endpoint_api_expand_itinerary_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/remove-specialist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Remove Specialist Endpoint
         * @description Remove specialists and regenerate itinerary (conflict resolution).
         *
         *     When ItineraryBuilder detects a constraint conflict (e.g., diving + hiking
         *     in 4 days), user can choose "Focus on diving". This endpoint:
         *     1. Removes other specialists from executed_strategy_topics
         *     2. Filters strategy_sections to keep only the kept specialist
         *     3. Clears day_cards (they'll be regenerated)
         *     4. Re-runs ItineraryBuilder with the simplified plan
         *
         *     Streams NDJSON events (same format as expand-itinerary):
         *         {"type": "progress", "stage": "itinerary", "message": "...", "pct": 30}
         *         {"type": "envelope", "plan_envelope": {...}}
         *         {"type": "done", "plan_view_state": "S3_ITINERARY_READY|S3_EDITING|S3_PARTIAL_CONFLICT"}
         *         {"type": "error", "message": "..."}
         */
        post: operations["remove_specialist_endpoint_api_remove_specialist_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AckUpdate
         * @description Detailed update info for collapsible message UI.
         */
        AckUpdate: {
            /** Field */
            field: string;
            /** To */
            to: string;
            /** From Value */
            from_value?: string | null;
        };
        /**
         * ActivitySettings
         * @description Activity-specific search settings.
         */
        ActivitySettings: {
            /** Categories */
            categories?: string[];
            /** Skill Level */
            skill_level?: string | null;
            /** Day Preferences */
            day_preferences?: {
                [key: string]: number;
            };
        };
        /**
         * BookingStatus
         * @description Per-tab booking status.
         */
        BookingStatus: {
            flights?: components["schemas"]["BookingStatusItem"] | null;
            stays?: components["schemas"]["BookingStatusItem"] | null;
            activities?: components["schemas"]["BookingStatusItem"] | null;
        };
        /**
         * BookingStatusItem
         * @description Status for a single booking category.
         */
        BookingStatusItem: {
            /**
             * State
             * @enum {string}
             */
            state: "idle" | "loading" | "ready" | "error";
            /** Summary */
            summary: string;
        };
        /**
         * BookingTypes
         * @description Which booking categories to search for.
         *
         *     Uses tri-state model:
         *     - 'off': User explicitly disabled, never show or search
         *     - 'suggested': Default state, show provisional items
         *     - 'on': User explicitly enabled, may require confirmation gates
         */
        BookingTypes: {
            /**
             * Hotels
             * @default suggested
             * @enum {string}
             */
            hotels: "off" | "suggested" | "on";
            /**
             * Flights
             * @default off
             * @enum {string}
             */
            flights: "off" | "suggested" | "on";
            /**
             * Ground Transport
             * @default off
             * @enum {string}
             */
            ground_transport: "off" | "suggested" | "on";
            /**
             * Activities
             * @default suggested
             * @enum {string}
             */
            activities: "off" | "suggested" | "on";
        };
        /**
         * BranchSelections
         * @description User's selected tile IDs for booking within a branch.
         */
        BranchSelections: {
            /** Stay */
            stay?: string | null;
            /** Flight */
            flight?: string | null;
            /** Activities */
            activities?: string[];
        };
        /**
         * BranchTileIds
         * @description Tile IDs grouped by vertical for a branch.
         */
        BranchTileIds: {
            /** Stays */
            stays?: string[];
            /** Flights */
            flights?: string[];
            /** Activities */
            activities?: string[];
        };
        /**
         * ChatHistoryResponse
         * @description Response containing chat history for a session.
         */
        ChatHistoryResponse: {
            /** Messages */
            messages: components["schemas"]["ChatMessageResponse"][];
        };
        /**
         * ChatMessageResponse
         * @description A single chat message for the frontend.
         */
        ChatMessageResponse: {
            /** Id */
            id: string;
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
            /** Content */
            content: string;
            /** Created At */
            created_at: string;
        };
        /**
         * Conflict
         * @description Structured conflict for UI rendering (no freeform text).
         */
        Conflict: {
            /**
             * Scope
             * @enum {string}
             */
            scope: "origin" | "destination" | "dates" | "travelers" | "budget";
            /** Related Constraints */
            related_constraints: ("origin" | "destination" | "dates" | "travelers" | "budget")[];
            /**
             * Code
             * @enum {string}
             */
            code: "date_range_invalid" | "date_past" | "budget_exceeded" | "traveler_mismatch" | "destination_unreachable" | "duration_mismatch";
        };
        /**
         * DayBlock
         * @description A single activity block within a day (Stage 3).
         */
        DayBlock: {
            /** Id */
            id?: string | null;
            /**
             * Period
             * @enum {string}
             */
            period: "morning" | "afternoon" | "evening";
            /** Activity Type */
            activity_type: string;
            /** Intensity */
            intensity?: ("light" | "moderate" | "challenging") | null;
            /** Summary */
            summary: string;
            /**
             * Is Buffer
             * @default false
             */
            is_buffer: boolean;
            /** Buffer Type */
            buffer_type?: ("no_fly" | "rest_day" | "acclimatization" | "arrival" | "departure") | null;
            /** Buffer Reason */
            buffer_reason?: string | null;
            /** Specialist Type */
            specialist_type?: string | null;
            /** Constraints */
            constraints?: string[];
            /** Image Url */
            image_url?: string | null;
            /** Duration */
            duration?: string | null;
            /** Coordinates */
            coordinates?: {
                [key: string]: number;
            } | null;
            /** Scheduled Time */
            scheduled_time?: string | null;
            /** Logistics Details */
            logistics_details?: string | null;
            /** Hotel Name */
            hotel_name?: string | null;
            /** Booked Tile */
            booked_tile?: {
                [key: string]: unknown;
            } | null;
            /**
             * Requires Booking
             * @default false
             */
            requires_booking: boolean;
            /** Booking Category */
            booking_category?: ("hotel" | "flight" | "activity") | null;
            /** Preference Status */
            preference_status?: ("user_preferred" | "ai_selected" | "ai_override") | null;
            /** Preference Override Reason */
            preference_override_reason?: string | null;
            /** Alternative Tile Id */
            alternative_tile_id?: string | null;
        };
        /**
         * DayCard
         * @description A single day in the itinerary (Stage 3).
         */
        DayCard: {
            /** Day Number */
            day_number: number;
            /** Date */
            date?: string | null;
            /** Label */
            label: string;
            /** Blocks */
            blocks?: components["schemas"]["DayBlock"][];
        };
        /**
         * DeleteLastMessageResponse
         * @description Response from deleting the last user message and its assistant response.
         */
        DeleteLastMessageResponse: {
            /** Deleted Count */
            deleted_count: number;
            /** Restored Trip Inputs */
            restored_trip_inputs?: {
                [key: string]: unknown;
            } | null;
            /** Messages */
            messages: components["schemas"]["ChatMessageResponse"][];
        };
        /**
         * DestinationCard
         * @description Destination content anchor for the plan.
         */
        DestinationCard: {
            /** Title */
            title: string;
            /** Subtitle */
            subtitle?: string | null;
            /** Image Url */
            image_url?: string | null;
        };
        /**
         * DestinationImageRequest
         * @description Request for destination image.
         */
        DestinationImageRequest: {
            /** Destination */
            destination: string;
        };
        /**
         * DestinationImageResponse
         * @description Response with destination image URL.
         */
        DestinationImageResponse: {
            /** Image Url */
            image_url: string;
            /** Destination */
            destination: string;
        };
        /**
         * DocumentBranch
         * @description A branch within the plan document.
         */
        DocumentBranch: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Description */
            description: string;
            /** Destination */
            destination?: string | null;
            /** Origin */
            origin?: string | null;
            /** Start Date */
            start_date?: string | null;
            /** End Date */
            end_date?: string | null;
            /** Adults */
            adults?: number | null;
            /** Children */
            children?: number | null;
            /** Requires Assistance */
            requires_assistance?: boolean | null;
            /** Budget */
            budget?: number | null;
            /**
             * Currency
             * @default USD
             */
            currency: string;
            /**
             * Is Primary
             * @default false
             */
            is_primary: boolean;
            tiles?: components["schemas"]["BranchTileIds"];
            selections?: components["schemas"]["BranchSelections"];
            /** Image Url */
            image_url?: string | null;
            /** Hero Images */
            hero_images?: string[];
            /** Vibe */
            vibe?: string | null;
            /** Focus */
            focus?: string | null;
            /** Highlights */
            highlights?: string[];
            /** Flow */
            flow?: string[];
            /** Notes */
            notes?: string[];
        };
        /**
         * DocumentTripInputs
         * @description Trip parameters extracted/inferred from conversation.
         */
        DocumentTripInputs: {
            /** Destination */
            destination?: string | null;
            /** Origin */
            origin?: string | null;
            /** Start Date */
            start_date?: string | null;
            /** End Date */
            end_date?: string | null;
            /** Adults */
            adults?: number | null;
            /** Children */
            children?: number | null;
            /** Requires Assistance */
            requires_assistance?: boolean | null;
            /** Budget */
            budget?: number | null;
            /**
             * Currency
             * @default USD
             */
            currency: string;
            /** Missing Fields */
            missing_fields?: string[];
            booking_types?: components["schemas"]["BookingTypes"];
            flight_settings?: components["schemas"]["FlightSettings"];
            hotel_settings?: components["schemas"]["HotelSettings"];
            activity_settings?: components["schemas"]["ActivitySettings"];
            transport_settings?: components["schemas"]["TransportSettings"];
            /**
             * Date Flex
             * @default false
             */
            date_flex: boolean;
            /** Trip Duration */
            trip_duration?: number | null;
            /** Date Window Start */
            date_window_start?: string | null;
            /** Date Window End */
            date_window_end?: string | null;
        };
        /**
         * DocumentTripInputsPatch
         * @description Partial trip-input updates coming from the UI or planner merges.
         */
        DocumentTripInputsPatch: {
            /** Destination */
            destination?: string | null;
            /** Origin */
            origin?: string | null;
            /** Start Date */
            start_date?: string | null;
            /** End Date */
            end_date?: string | null;
            /** Adults */
            adults?: number | null;
            /** Children */
            children?: number | null;
            /** Requires Assistance */
            requires_assistance?: boolean | null;
            /** Budget */
            budget?: number | null;
            /** Currency */
            currency?: string | null;
            /** Missing Fields */
            missing_fields?: string[] | null;
            booking_types?: components["schemas"]["BookingTypes"] | null;
            flight_settings?: components["schemas"]["FlightSettings"] | null;
            hotel_settings?: components["schemas"]["HotelSettings"] | null;
            activity_settings?: components["schemas"]["ActivitySettings"] | null;
        };
        /**
         * EntityConfidenceInfo
         * @description Confidence information for a single extracted entity (e.g., destination).
         */
        EntityConfidenceInfo: {
            /** Value */
            value: string;
            /** Confidence */
            confidence: number;
            /**
             * Needs Confirmation
             * @default false
             */
            needs_confirmation: boolean;
            /** Fuzzy Suggestion */
            fuzzy_suggestion?: string | null;
            /** Ambiguity Type */
            ambiguity_type?: string | null;
        };
        /**
         * ExpandItineraryRequest
         * @description Request to expand strategy into full itinerary (Stage 2 -> Stage 3).
         */
        ExpandItineraryRequest: {
            /**
             * Idempotency Key
             * @description Client-generated UUID to prevent duplicate generation
             */
            idempotency_key: string;
            /**
             * Trip Inputs
             * @description Trip inputs from frontend document
             */
            trip_inputs?: {
                [key: string]: unknown;
            } | null;
            /**
             * Strategy Sections
             * @description Strategy sections from frontend document
             */
            strategy_sections?: {
                [key: string]: unknown;
            }[] | null;
            /**
             * Tiles
             * @description Tiles from frontend document
             */
            tiles?: {
                [key: string]: unknown;
            } | null;
            /** @description User's hearted tile preferences for AI weighting */
            preferences?: components["schemas"]["PreferenceOverride"] | null;
            /**
             * Force Full Rebuild
             * @description Force full itinerary rebuild, bypassing selective regeneration
             * @default false
             */
            force_full_rebuild: boolean;
        };
        /**
         * ExtractionConfidenceInfo
         * @description Overall extraction confidence for the current request.
         */
        ExtractionConfidenceInfo: {
            /**
             * Overall
             * @default 1
             */
            overall: number;
            /**
             * Level
             * @default high
             */
            level: string;
            /** Destinations */
            destinations?: components["schemas"]["EntityConfidenceInfo"][];
            origin?: components["schemas"]["EntityConfidenceInfo"] | null;
            /** Detected Language */
            detected_language?: string | null;
            /**
             * Is English
             * @default true
             */
            is_english: boolean;
            /** Typo Suggestions */
            typo_suggestions?: string[];
        };
        /**
         * FillDayRequest
         * @description Request to fill a free day with activity tiles.
         */
        FillDayRequest: {
            /** Day Number */
            day_number: number;
            /** Categories */
            categories?: string[] | null;
            /** Pinned Tile Ids */
            pinned_tile_ids?: string[] | null;
        };
        /**
         * FlightSettings
         * @description Flight-specific search settings.
         */
        FlightSettings: {
            /**
             * Round Trip
             * @default true
             */
            round_trip: boolean;
            /**
             * Cabin Class
             * @default economy
             * @enum {string}
             */
            cabin_class: "economy" | "premium_economy" | "business" | "first";
            /**
             * Direct Only
             * @default false
             */
            direct_only: boolean;
        };
        /** Geo */
        Geo: {
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
        };
        /**
         * GraphPlanObservability
         * @description Minimal observability data for /v1/graph_plan responses.
         */
        GraphPlanObservability: {
            tokens?: components["schemas"]["GraphPlanTokens"];
            /** Model Used */
            model_used?: string | null;
            /** Router Intent */
            router_intent?: string | null;
            /** Strategy Topic */
            strategy_topic?: string | null;
            /** Today Iso */
            today_iso?: string | null;
            /**
             * Ready To Generate Prev
             * @default false
             */
            ready_to_generate_prev: boolean;
            /**
             * Ready To Generate Now
             * @default false
             */
            ready_to_generate_now: boolean;
            extraction_confidence?: components["schemas"]["ExtractionConfidenceInfo"] | null;
            /** Short Circuit Type */
            short_circuit_type?: string | null;
            /**
             * Llm Calls Made
             * @default 0
             */
            llm_calls_made: number;
            /**
             * Cache Hits
             * @default 0
             */
            cache_hits: number;
            /** Confidence Routing */
            confidence_routing?: string | null;
        };
        /**
         * GraphPlanRequest
         * @description Request schema for graph-based planning entrypoint.
         */
        GraphPlanRequest: {
            /** Message */
            message: string;
            /** Trip Inputs */
            trip_inputs?: {
                [key: string]: unknown;
            };
            /** Session State */
            session_state?: {
                [key: string]: unknown;
            } | null;
            /**
             * Document Id
             * @description Optional document ID for persistence and optimistic concurrency
             */
            document_id?: string | null;
            /**
             * Expected Version
             * @description Expected document version for optimistic concurrency control
             */
            expected_version?: number | null;
            /**
             * Thread Id
             * @description Optional thread ID for conversation tracking
             */
            thread_id?: string | null;
            /**
             * Reset
             * @description When true with empty session_state, generate new thread_id and optionally init from trip_inputs
             * @default false
             */
            reset: boolean;
            /** Ui Phase */
            ui_phase?: ("bootstrap" | "expanded") | null;
            /** Suggestion Clicked */
            suggestion_clicked?: string | null;
        };
        /**
         * GraphPlanResponse
         * @description Response from /v1/graph_plan endpoint.
         */
        GraphPlanResponse: {
            document: components["schemas"]["PlanDocumentData"];
            /** Session State */
            session_state: {
                [key: string]: unknown;
            };
            /** Version */
            version: number;
            /**
             * Updated By
             * @enum {string}
             */
            updated_by: "user" | "planner";
            /** Updated At */
            updated_at: string;
            /**
             * Changes Made
             * @default false
             */
            changes_made: boolean;
            /** Request Id */
            request_id: string;
            observability?: components["schemas"]["GraphPlanObservability"] | null;
        };
        /**
         * GraphPlanTokens
         * @description Token usage for observability.
         */
        GraphPlanTokens: {
            /**
             * Prompt
             * @default 0
             */
            prompt: number;
            /**
             * Completion
             * @default 0
             */
            completion: number;
            /**
             * Total
             * @default 0
             */
            total: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HotelSettings
         * @description Hotel-specific search settings.
         */
        HotelSettings: {
            /**
             * Min Stars
             * @default 0
             */
            min_stars: number;
            /** Amenities */
            amenities?: string[];
        };
        /**
         * ItineraryAssumptions
         * @description Assumptions and flexible elements for Stage 3.
         */
        ItineraryAssumptions: {
            /** Assumptions */
            assumptions?: string[];
            /** Flexible Elements */
            flexible_elements?: string[];
        };
        /**
         * ItineraryOverview
         * @description Overview stats for Stage 3 itinerary.
         */
        ItineraryOverview: {
            /** Duration Label */
            duration_label: string;
            /** Base Structure */
            base_structure: string;
            /** Activity Density */
            activity_density: string;
        };
        /**
         * OpenDecision
         * @description An open decision that needs user input (shown in Stage 2).
         */
        OpenDecision: {
            /** Id */
            id: string;
            /** Statement */
            statement: string;
            /** Related Field */
            related_field?: string | null;
            /**
             * Is Blocking
             * @default false
             */
            is_blocking: boolean;
        };
        /**
         * PlanDocumentData
         * @description The JSON structure stored in plan_documents.document column.
         *     This is the source of truth for the planning session.
         */
        PlanDocumentData: {
            /** Trip Context Id */
            trip_context_id?: number | null;
            trip_inputs?: components["schemas"]["DocumentTripInputs"];
            /** Branches */
            branches?: components["schemas"]["DocumentBranch"][];
            /** Tiles */
            tiles?: {
                [key: string]: components["schemas"]["Tile"];
            };
            /** Assistant Message */
            assistant_message?: string | null;
            /** Assistant Message Id */
            assistant_message_id?: string | null;
            /**
             * Ready To Generate
             * @default false
             */
            ready_to_generate: boolean;
            /** Suggested Responses */
            suggested_responses?: string[];
            /** Suggested Response Meta */
            suggested_response_meta?: {
                [key: string]: unknown;
            }[];
            /** Suggestion Chips */
            suggestion_chips?: components["schemas"]["SuggestionChip"][];
            /** Applied Updates */
            applied_updates?: ("origin" | "destination" | "dates" | "travelers" | "budget")[];
            /** Conflicts */
            conflicts?: components["schemas"]["Conflict"][];
            /** Undo Snapshot */
            undo_snapshot?: {
                [key: string]: unknown;
            } | null;
            /** Update Provenance */
            update_provenance?: ("lqa" | "extractor" | "user_edit") | null;
            /**
             * Ack Status
             * @default applied
             * @enum {string}
             */
            ack_status: "applied" | "partial" | "no_change" | "needs_clarification" | "failed" | "rejected";
            /** Ack Updates */
            ack_updates?: components["schemas"]["AckUpdate"][];
            /**
             * Plan State
             * @default INCOMPLETE
             * @enum {string}
             */
            plan_state: "INCOMPLETE" | "RESOLVING" | "STABLE" | "LOCKED";
            /**
             * Ui Phase
             * @default bootstrap
             * @enum {string}
             */
            ui_phase: "bootstrap" | "expanded";
            resolver?: components["schemas"]["ResolverState"] | null;
            /** Readiness */
            readiness?: components["schemas"]["ReadinessItem"][];
            destination_card?: components["schemas"]["DestinationCard"] | null;
            booking_status?: components["schemas"]["BookingStatus"] | null;
            /**
             * Plan View State
             * @default P0_MINIMAL
             * @enum {string}
             */
            plan_view_state: "P0_MINIMAL" | "P1_ENRICHED" | "P2_LOGISTICS" | "P3_FINALIZED" | "P3_EDITING" | "P3_BLOCKED" | "S0_BOOTSTRAP" | "S1_FRAMING" | "S2_STRATEGY_READY" | "S2_BLOCKED" | "S3_ITINERARY_READY" | "S3_EDITING" | "S3_PARTIAL_CONFLICT" | "S3_BLOCKED";
            /** Strategy Sections */
            strategy_sections?: components["schemas"]["StrategySection"][];
            /** Executed Strategy Topics */
            executed_strategy_topics?: string[];
            /** Pending Strategy Topics */
            pending_strategy_topics?: string[];
            /** Open Decisions */
            open_decisions?: components["schemas"]["OpenDecision"][];
            itinerary_overview?: components["schemas"]["ItineraryOverview"] | null;
            /** Day Cards */
            day_cards?: components["schemas"]["DayCard"][];
            itinerary_assumptions?: components["schemas"]["ItineraryAssumptions"] | null;
            /**
             * Needs Refresh
             * @default false
             */
            needs_refresh: boolean;
            /**
             * Can Expand To Itinerary
             * @default false
             */
            can_expand_to_itinerary: boolean;
            /** Preferred Tile Ids */
            preferred_tile_ids?: string[];
            /**
             * Origin Just Set
             * @default false
             */
            origin_just_set: boolean;
            /**
             * Tiles Replaced
             * @default false
             */
            tiles_replaced: boolean;
            /** User Pinned Tiles */
            user_pinned_tiles?: {
                [key: string]: unknown;
            };
            /** Constraints Validated */
            constraints_validated?: {
                [key: string]: unknown;
            }[];
            /** Constraint Violations */
            constraint_violations?: {
                [key: string]: unknown;
            }[];
        };
        /**
         * PlanDocumentPatch
         * @description Partial update to the plan document from the user.
         *     Uses CRDT-style merge: additions win, deletions require explicit flags.
         */
        PlanDocumentPatch: {
            /** Version */
            version: number;
            /** Branches */
            branches?: components["schemas"]["DocumentBranch"][] | null;
            /** Remove Branch Ids */
            remove_branch_ids?: string[] | null;
            /** Tiles */
            tiles?: {
                [key: string]: components["schemas"]["Tile"];
            } | null;
            /** Remove Tile Ids */
            remove_tile_ids?: string[] | null;
            /** Selections */
            selections?: {
                [key: string]: components["schemas"]["BranchSelections"];
            } | null;
            /** Trip Inputs */
            trip_inputs?: components["schemas"]["DocumentTripInputsPatch"] | components["schemas"]["DocumentTripInputs"] | null;
            /** Preferred Tile Ids */
            preferred_tile_ids?: string[] | null;
        };
        /**
         * PlanDocumentResponse
         * @description Response when fetching the plan document.
         */
        PlanDocumentResponse: {
            /** Version */
            version: number;
            /**
             * Updated By
             * @enum {string}
             */
            updated_by: "user" | "planner";
            document: components["schemas"]["PlanDocumentData"];
            /** Updated At */
            updated_at: string;
            /**
             * Changes Made
             * @default false
             */
            changes_made: boolean;
        };
        /**
         * PreferenceOverride
         * @description User's heart preferences for AI weighting in itinerary generation.
         */
        PreferenceOverride: {
            /**
             * Preferred Hotel Ids
             * @description Tile IDs of hotels the user has hearted/preferred
             */
            preferred_hotel_ids?: string[];
            /**
             * Preferred Activity Ids
             * @description Tile IDs of activities the user has hearted/preferred
             */
            preferred_activity_ids?: string[];
            /**
             * Preferred Flight Ids
             * @description Tile IDs of flights the user has hearted/preferred
             */
            preferred_flight_ids?: string[];
        };
        /**
         * ReadinessItem
         * @description Single readiness constraint status.
         */
        ReadinessItem: {
            /**
             * Key
             * @enum {string}
             */
            key: "origin" | "destination" | "start_date" | "end_date" | "travelers" | "budget";
            /** Ok */
            ok: boolean;
        };
        /**
         * RemoveSpecialistRequest
         * @description Request to remove specialists and regenerate itinerary (conflict resolution).
         *
         *     Used when ItineraryBuilder detects a constraint conflict and user chooses
         *     to focus on one specialist (e.g., "Focus on diving" when diving + hiking conflicts).
         */
        RemoveSpecialistRequest: {
            /**
             * Idempotency Key
             * @description Client-generated UUID to prevent duplicate generation
             */
            idempotency_key: string;
            /**
             * Keep Specialist
             * @description The specialist to keep (e.g., 'diving', 'hiking')
             */
            keep_specialist: string;
            /**
             * Remove Hearted Tiles
             * @description If true, removes hearted tiles from removed specialists
             * @default false
             */
            remove_hearted_tiles: boolean;
            /**
             * Trip Inputs
             * @description Trip inputs from frontend document
             */
            trip_inputs?: {
                [key: string]: unknown;
            } | null;
            /**
             * Strategy Sections
             * @description Strategy sections from frontend document
             */
            strategy_sections?: {
                [key: string]: unknown;
            }[] | null;
            /**
             * Tiles
             * @description Tiles from frontend document
             */
            tiles?: {
                [key: string]: unknown;
            } | null;
            /** @description User's hearted tile preferences for AI weighting */
            preferences?: components["schemas"]["PreferenceOverride"] | null;
        };
        /**
         * ResolverState
         * @description Resolver progress for RESOLVING state.
         */
        ResolverState: {
            /**
             * Active Step
             * @enum {string}
             */
            active_step: "processing_constraints" | "matching_inventory" | "updating_itinerary";
            /** Completed Steps */
            completed_steps?: ("processing_constraints" | "matching_inventory" | "updating_itinerary")[];
        };
        /**
         * StrategySection
         * @description A strategy section for Stage 2 view - one card per executed strategy topic.
         */
        StrategySection: {
            /** Id */
            id: string;
            /**
             * Title
             * @default Strategy
             */
            title: string;
            /** Subtitle */
            subtitle?: string | null;
            /** Specialist Type */
            specialist_type?: string | null;
            /** Feasibility Status */
            feasibility_status?: string | null;
            /** Feasibility Reason */
            feasibility_reason?: string | null;
            /** Alternative Suggestion */
            alternative_suggestion?: string | null;
            /** One Liner */
            one_liner?: string | null;
            /** Principles */
            principles?: string[];
            /** Must Dos */
            must_dos?: string[];
            /** Optional Upgrades */
            optional_upgrades?: string[];
            /** Logistics Notes */
            logistics_notes?: string[];
            /** Tradeoffs Summary */
            tradeoffs_summary?: string | null;
            /** Strategy Node Id */
            strategy_node_id?: string | null;
            /** Strategy Version */
            strategy_version?: string | null;
            /** Booking Artifacts */
            booking_artifacts?: {
                [key: string]: number;
            } | null;
            /** Impact Areas */
            impact_areas?: string[];
            /** Constraints Applied */
            constraints_applied?: {
                [key: string]: string;
            }[];
            /** Content Added */
            content_added?: {
                [key: string]: unknown;
            }[];
            /** Content Blocks */
            content_blocks?: {
                [key: string]: unknown;
            }[];
            /** Editorial One Liner */
            editorial_one_liner?: string | null;
            /** Vibe Trio */
            vibe_trio?: {
                [key: string]: string;
            }[] | null;
            /** Hero Image */
            hero_image?: string | null;
            /** Travel Intelligence */
            travel_intelligence?: {
                [key: string]: unknown;
            } | null;
            /** Destination Gallery */
            destination_gallery?: {
                [key: string]: string;
            }[];
            /** Trip Summary */
            trip_summary?: {
                [key: string]: unknown;
            } | null;
            /** Bullets */
            bullets?: string[];
        };
        /**
         * SuggestionChip
         * @description Structured suggestion chip with action routing.
         */
        SuggestionChip: {
            /** Message */
            message: string;
            /**
             * Action Type
             * @default send_message
             * @enum {string}
             */
            action_type: "send_message" | "open_pill" | "trigger_action";
            /** Action Target */
            action_target?: string | null;
            /**
             * Chip Type
             * @default follow_up
             * @enum {string}
             */
            chip_type: "cta" | "follow_up" | "setting";
            /**
             * Category
             * @default
             */
            category: string;
            /** Icon */
            icon?: string | null;
        };
        /**
         * SuggestionClickEvent
         * @description Track when a user clicks a suggested response pill.
         */
        SuggestionClickEvent: {
            /** Suggestion Text */
            suggestion_text: string;
            /** Suggestion Index */
            suggestion_index: number;
            /** Request Id */
            request_id?: string | null;
        };
        /** Tile */
        Tile: {
            /** Id */
            id: string;
            /**
             * Type
             * @enum {string}
             */
            type: "flight" | "hotel" | "activity";
            /** Partner */
            partner: string;
            /** Partner Product Id */
            partner_product_id: string;
            /** Title */
            title: string;
            /** Subtitle */
            subtitle?: string | null;
            /** Image Url */
            image_url?: string | null;
            /** Price Estimate */
            price_estimate?: number | null;
            /** Live Price */
            live_price?: number | null;
            /**
             * Currency
             * @default USD
             */
            currency: string;
            /**
             * Price Basis
             * @default per_trip
             */
            price_basis: string;
            /**
             * Is Estimate Only
             * @default true
             */
            is_estimate_only: boolean;
            /** Deeplink Url */
            deeplink_url: string;
            /** Rating */
            rating?: number | null;
            /** Review Count */
            review_count?: number | null;
            /** Location Label */
            location_label?: string | null;
            geo?: components["schemas"]["Geo"] | null;
            /** Tags */
            tags?: string[];
            /**
             * Availability Status
             * @default unknown
             * @enum {string}
             */
            availability_status: "available" | "low" | "unknown" | "not_available";
            /** Meta */
            meta?: {
                [key: string]: unknown;
            };
            /** Score */
            score?: number | null;
            /** Source */
            source?: string | null;
            /** Source Agent */
            source_agent?: string | null;
            /** Total Inclusive */
            total_inclusive?: number | null;
            /** Tax And Service Fee */
            tax_and_service_fee?: number | null;
            /** Property Fee */
            property_fee?: number | null;
            /** Is Refundable */
            is_refundable?: boolean | null;
            /** Cancel Policy Summary */
            cancel_policy_summary?: string | null;
            /**
             * Provider
             * @default expedia
             */
            provider: ("expedia" | "booking" | "unknown") | null;
        };
        /** TileClickEvent */
        TileClickEvent: {
            /** Request Id */
            request_id?: string | null;
            /** Tile Id */
            tile_id: string;
            /** Branch Id */
            branch_id?: string | null;
        };
        /**
         * TileRefreshRequest
         * @description Request to refresh tiles with current settings.
         */
        TileRefreshRequest: {
            /** Branch Id */
            branch_id: string;
            /** Verticals */
            verticals?: ("flight" | "hotel" | "activity")[] | null;
        };
        /**
         * TileRefreshResponse
         * @description Response from tile refresh.
         */
        TileRefreshResponse: {
            /** Tiles */
            tiles: components["schemas"]["Tile"][];
            /** Refreshed At */
            refreshed_at: string;
            /** Verticals Refreshed */
            verticals_refreshed: string[];
        };
        /**
         * TransportSettings
         * @description Ground transport settings - which modes to include.
         */
        TransportSettings: {
            /**
             * Car
             * @default false
             */
            car: boolean;
            /**
             * Train
             * @default false
             */
            train: boolean;
            /**
             * Bus
             * @default false
             */
            bus: boolean;
        };
        /**
         * TripInputValidationRequest
         * @description Request to validate a trip input (origin or destination).
         */
        TripInputValidationRequest: {
            /**
             * Field Type
             * @enum {string}
             */
            field_type: "origin" | "destination";
            /** Value */
            value: string;
        };
        /**
         * TripInputValidationResponse
         * @description Response from trip input validation.
         */
        TripInputValidationResponse: {
            /** Corrected Values */
            corrected_values: string[];
            /** Is Valid */
            is_valid: boolean;
            /** Reason */
            reason?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    validate_trip_input_api_validate_trip_input_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripInputValidationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripInputValidationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_destination_image_api_destination_image_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DestinationImageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DestinationImageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_clear_validation_cache_api_admin_clear_validation_cache_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    admin_fresh_start_api_admin_fresh_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    admin_graph_stats_api_admin_graph_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    admin_planner_debug_api_admin_planner_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    admin_clear_all_checkpoints_api_admin_clear_all_checkpoints_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    admin_clear_all_caches_api_admin_clear_all_caches_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    admin_specialist_cache_stats_api_admin_specialist_cache_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    admin_clear_specialist_cache_api_admin_clear_specialist_cache_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    admin_tile_cache_stats_api_admin_tile_cache_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    admin_clear_tile_cache_api_admin_clear_tile_cache_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    admin_router_cache_stats_api_admin_router_cache_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    admin_clear_router_cache_api_admin_clear_router_cache_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    admin_all_cache_stats_api_admin_cache_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    track_tile_click_api_tiles_click_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TileClickEvent"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    track_suggestion_click_api_suggestions_click_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SuggestionClickEvent"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    graph_plan_endpoint_api_graph_plan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GraphPlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphPlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    graph_plan_stream_endpoint_api_graph_plan_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GraphPlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_session_api_session_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_chat_history_api_chat_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatHistoryResponse"];
                };
            };
        };
    };
    delete_last_message_api_chat_last_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteLastMessageResponse"];
                };
            };
        };
    };
    get_plan_document_api_document_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanDocumentResponse"];
                };
            };
        };
    };
    patch_plan_document_api_document_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanDocumentPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanDocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fetch_tiles_for_branch_api_document_tiles__branch_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                branch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanDocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_tiles_api_tiles_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TileRefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TileRefreshResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fill_day_endpoint_api_document_fill_day_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FillDayRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    expand_itinerary_endpoint_api_expand_itinerary_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExpandItineraryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_specialist_endpoint_api_remove_specialist_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RemoveSpecialistRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
