/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/validate-trip-input": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate Trip Input
         * @description Validate a trip input (origin, destination, or vibe).
         *
         *     Returns corrected values if the input was valid but had typos/formatting issues.
         *     For destinations, may return multiple values if the input contained multiple
         *     places (e.g., "Paris and Rome" -> ["Paris", "Rome"]).
         *
         *     Raises HTTP 503 if validation fails after retries.
         */
        post: operations["validate_trip_input_v1_validate_trip_input_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/clear-validation-cache": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Admin Clear Validation Cache
         * @description Clear the validation cache. For development/debugging only.
         */
        post: operations["admin_clear_validation_cache_v1_admin_clear_validation_cache_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tiles/click": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Track Tile Click
         * @description Persist a tile click for analytics.
         */
        post: operations["track_tile_click_v1_tiles_click_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Plan
         * @description Chat-like planning endpoint:
         *     message + preferences -> branches via LLM -> tiles for primary branch.
         *     Returns the full plan document with branches, tiles, and chat response.
         *
         *     Session rotation:
         *     After the first trip context is created, the session token is rotated
         *     to prevent session fixation attacks. New cookies are set on the response.
         */
        post: operations["plan_v1_plan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Reset Session
         * @description Reset/delete a planning session and all associated data.
         *
         *     Uses row-level locking to prevent deadlocks with concurrent plan operations.
         *     Also clears session cookies from the browser.
         */
        delete: operations["reset_session_v1_session_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Chat History
         * @description Get chat history for the current session.
         *
         *     Returns the last 50 messages in chronological order (oldest first).
         *     Used by the frontend to restore chat state on page load.
         */
        get: operations["get_chat_history_v1_chat_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/document": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Plan Document
         * @description Get the current plan document for a session.
         *     Returns the centralized source of truth for branches and tiles.
         */
        get: operations["get_plan_document_v1_document_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Plan Document
         * @description Apply a partial update to the plan document.
         *     Uses CRDT-style merge: additions win, deletions require explicit flags.
         */
        patch: operations["patch_plan_document_v1_document_patch"];
        trace?: never;
    };
    "/v1/document/tiles/{branch_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Fetch Tiles For Branch
         * @description Fetch tiles for a specific branch and add them to the document.
         *     Used when switching branches to load tiles on demand.
         */
        post: operations["fetch_tiles_for_branch_v1_document_tiles__branch_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActivitySettings
         * @description Activity-specific search settings.
         */
        ActivitySettings: {
            /** Categories */
            categories?: string[];
            /** Max Duration Hours */
            max_duration_hours?: number | null;
        };
        /**
         * BookingTypes
         * @description Which booking categories to search for.
         */
        BookingTypes: {
            /**
             * Hotels
             * @default false
             */
            hotels: boolean;
            /**
             * Flights
             * @default false
             */
            flights: boolean;
            /**
             * Ground Transport
             * @default false
             */
            ground_transport: boolean;
            /**
             * Activities
             * @default false
             */
            activities: boolean;
        };
        /**
         * BranchSelections
         * @description User's selected tile IDs for booking within a branch.
         */
        BranchSelections: {
            /** Stay */
            stay?: string | null;
            /** Flight */
            flight?: string | null;
            /** Activities */
            activities?: string[];
        };
        /**
         * BranchTileIds
         * @description Tile IDs grouped by vertical for a branch.
         */
        BranchTileIds: {
            /** Stays */
            stays?: string[];
            /** Flights */
            flights?: string[];
            /** Activities */
            activities?: string[];
        };
        /**
         * ChatHistoryResponse
         * @description Response containing chat history for a session.
         */
        ChatHistoryResponse: {
            /** Messages */
            messages: components["schemas"]["ChatMessageResponse"][];
        };
        /**
         * ChatMessageResponse
         * @description A single chat message for the frontend.
         */
        ChatMessageResponse: {
            /** Id */
            id: string;
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
            /** Content */
            content: string;
            /** Created At */
            created_at: string;
        };
        /**
         * DocumentBranch
         * @description A branch within the plan document.
         */
        DocumentBranch: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Description */
            description: string;
            /** Destinations */
            destinations?: string[];
            /** Origin */
            origin?: string | null;
            /** Start Date */
            start_date?: string | null;
            /** End Date */
            end_date?: string | null;
            /** Adults */
            adults?: number | null;
            /** Children */
            children?: number | null;
            /** Requires Assistance */
            requires_assistance?: boolean | null;
            /** Budget */
            budget?: number | null;
            /** Currency */
            currency?: string | null;
            /**
             * Is Primary
             * @default false
             */
            is_primary: boolean;
            tiles?: components["schemas"]["BranchTileIds"];
            selections?: components["schemas"]["BranchSelections"];
        };
        /**
         * DocumentTripInputs
         * @description Trip parameters extracted/inferred from conversation.
         */
        DocumentTripInputs: {
            /** Destinations */
            destinations?: string[];
            /** Origin */
            origin?: string | null;
            /** Start Date */
            start_date?: string | null;
            /** End Date */
            end_date?: string | null;
            /** Adults */
            adults?: number | null;
            /** Children */
            children?: number | null;
            /** Requires Assistance */
            requires_assistance?: boolean | null;
            /** Budget */
            budget?: number | null;
            /** Currency */
            currency?: string | null;
            /** Missing Fields */
            missing_fields?: string[];
            /** Multi City Intent */
            multi_city_intent?: ("multi_city" | "separate") | null;
            /** Vibes */
            vibes?: string[];
            booking_types?: components["schemas"]["BookingTypes"];
            flight_settings?: components["schemas"]["FlightSettings"];
            hotel_settings?: components["schemas"]["HotelSettings"];
            activity_settings?: components["schemas"]["ActivitySettings"];
            transport_settings?: components["schemas"]["TransportSettings"];
        };
        /**
         * DocumentTripInputsPatch
         * @description Partial trip-input updates coming from the UI or planner merges.
         */
        DocumentTripInputsPatch: {
            /** Destinations */
            destinations?: string[] | null;
            /** Origin */
            origin?: string | null;
            /** Start Date */
            start_date?: string | null;
            /** End Date */
            end_date?: string | null;
            /** Adults */
            adults?: number | null;
            /** Children */
            children?: number | null;
            /** Requires Assistance */
            requires_assistance?: boolean | null;
            /** Budget */
            budget?: number | null;
            /** Currency */
            currency?: string | null;
            /** Missing Fields */
            missing_fields?: string[] | null;
            /** Multi City Intent */
            multi_city_intent?: ("multi_city" | "separate") | null;
            /** Vibes */
            vibes?: string[] | null;
            booking_types?: components["schemas"]["BookingTypes"] | null;
            flight_settings?: components["schemas"]["FlightSettings"] | null;
            hotel_settings?: components["schemas"]["HotelSettings"] | null;
            activity_settings?: components["schemas"]["ActivitySettings"] | null;
        };
        /**
         * FlightSettings
         * @description Flight-specific search settings.
         */
        FlightSettings: {
            /**
             * Round Trip
             * @default true
             */
            round_trip: boolean;
            /**
             * Cabin Class
             * @default economy
             * @enum {string}
             */
            cabin_class: "economy" | "premium_economy" | "business" | "first";
            /**
             * Direct Only
             * @default false
             */
            direct_only: boolean;
        };
        /** Geo */
        Geo: {
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HotelSettings
         * @description Hotel-specific search settings.
         */
        HotelSettings: {
            /**
             * Min Stars
             * @default 0
             */
            min_stars: number;
            /** Amenities */
            amenities?: string[];
        };
        /**
         * PlanDocumentData
         * @description The JSON structure stored in plan_documents.document column.
         *     This is the source of truth for the planning session.
         */
        PlanDocumentData: {
            /** Trip Context Id */
            trip_context_id?: number | null;
            trip_inputs?: components["schemas"]["DocumentTripInputs"];
            /** Branches */
            branches?: components["schemas"]["DocumentBranch"][];
            /** Tiles */
            tiles?: {
                [key: string]: components["schemas"]["Tile"];
            };
            /** Assistant Message */
            assistant_message?: string | null;
            /** Assistant Message Id */
            assistant_message_id?: string | null;
            /**
             * Ready To Generate
             * @default false
             */
            ready_to_generate: boolean;
        };
        /**
         * PlanDocumentPatch
         * @description Partial update to the plan document from the user.
         *     Uses CRDT-style merge: additions win, deletions require explicit flags.
         */
        PlanDocumentPatch: {
            /** Version */
            version: number;
            /** Branches */
            branches?: components["schemas"]["DocumentBranch"][] | null;
            /** Remove Branch Ids */
            remove_branch_ids?: string[] | null;
            /** Tiles */
            tiles?: {
                [key: string]: components["schemas"]["Tile"];
            } | null;
            /** Remove Tile Ids */
            remove_tile_ids?: string[] | null;
            /** Selections */
            selections?: {
                [key: string]: components["schemas"]["BranchSelections"];
            } | null;
            /** Trip Inputs */
            trip_inputs?: components["schemas"]["DocumentTripInputsPatch"] | components["schemas"]["DocumentTripInputs"] | null;
        };
        /**
         * PlanDocumentResponse
         * @description Response when fetching the plan document.
         */
        PlanDocumentResponse: {
            /** Version */
            version: number;
            /**
             * Updated By
             * @enum {string}
             */
            updated_by: "user" | "planner";
            document: components["schemas"]["PlanDocumentData"];
            /** Updated At */
            updated_at: string;
            /**
             * Changes Made
             * @default false
             */
            changes_made: boolean;
        };
        /**
         * PlanRequest
         * @description Request to send a chat message to the planner.
         *
         *     Note: Trip inputs are read from the PlanDocument (single source of truth).
         *     The frontend should NOT send trip_inputs directly - all state flows through
         *     the document.
         *
         *     Note: session_id is no longer in the request body - it comes from the
         *     HttpOnly session cookie, injected by SessionMiddleware.
         */
        PlanRequest: {
            /** Message */
            message: string;
            /** Timezone */
            timezone?: string | null;
        };
        /** Tile */
        Tile: {
            /** Id */
            id: string;
            /**
             * Type
             * @enum {string}
             */
            type: "flight" | "hotel" | "activity";
            /** Partner */
            partner: string;
            /** Partner Product Id */
            partner_product_id: string;
            /** Title */
            title: string;
            /** Subtitle */
            subtitle?: string | null;
            /** Image Url */
            image_url?: string | null;
            /** Price Estimate */
            price_estimate?: number | null;
            /** Live Price */
            live_price?: number | null;
            /**
             * Currency
             * @default EUR
             */
            currency: string;
            /**
             * Price Basis
             * @default per_trip
             */
            price_basis: string;
            /**
             * Is Estimate Only
             * @default true
             */
            is_estimate_only: boolean;
            /** Deeplink Url */
            deeplink_url: string;
            /** Rating */
            rating?: number | null;
            /** Review Count */
            review_count?: number | null;
            /** Location Label */
            location_label?: string | null;
            geo?: components["schemas"]["Geo"] | null;
            /** Tags */
            tags?: string[];
            /**
             * Availability Status
             * @default unknown
             * @enum {string}
             */
            availability_status: "available" | "low" | "unknown" | "not_available";
            /** Meta */
            meta?: {
                [key: string]: unknown;
            };
            /** Score */
            score?: number | null;
            /** Source */
            source?: string | null;
        };
        /** TileClickEvent */
        TileClickEvent: {
            /** Request Id */
            request_id?: string | null;
            /** Tile Id */
            tile_id: string;
            /** Branch Id */
            branch_id?: string | null;
        };
        /**
         * TransportSettings
         * @description Ground transport settings - which modes to include.
         */
        TransportSettings: {
            /**
             * Car
             * @default false
             */
            car: boolean;
            /**
             * Train
             * @default false
             */
            train: boolean;
            /**
             * Bus
             * @default false
             */
            bus: boolean;
        };
        /**
         * TripInputValidationRequest
         * @description Request to validate a trip input (origin, destination, or vibe).
         */
        TripInputValidationRequest: {
            /**
             * Field Type
             * @enum {string}
             */
            field_type: "origin" | "destination" | "vibe";
            /** Value */
            value: string;
        };
        /**
         * TripInputValidationResponse
         * @description Response from trip input validation.
         */
        TripInputValidationResponse: {
            /** Corrected Values */
            corrected_values: string[];
            /** Is Valid */
            is_valid: boolean;
            /** Reason */
            reason?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    validate_trip_input_v1_validate_trip_input_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripInputValidationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripInputValidationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_clear_validation_cache_v1_admin_clear_validation_cache_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    track_tile_click_v1_tiles_click_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TileClickEvent"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    plan_v1_plan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanDocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_session_v1_session_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_chat_history_v1_chat_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatHistoryResponse"];
                };
            };
        };
    };
    get_plan_document_v1_document_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanDocumentResponse"];
                };
            };
        };
    };
    patch_plan_document_v1_document_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanDocumentPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanDocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fetch_tiles_for_branch_v1_document_tiles__branch_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                branch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanDocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
