"""
V2 State Schemas - Simplified "Core + Specialist" Architecture.

This module defines the state models for the 6-node architecture:
- TripPlan: Single Source of Truth for the trip
- TripSegment: Individual booking segment (flight/hotel/activity)
- ItineraryBlock: Specialist-generated content (activities, experiences)
- SpecialistConstraint: Domain constraints from Vertical Specialist
- GraphStateV2: Unified state for the new architecture

Key Principle: Architect sees the whole picture.
"""

from typing import Any, Dict, List, Literal, Optional

from langchain_core.messages import BaseMessage
from pydantic import BaseModel, Field

# =============================================================================
# Trip Plan Models (SSoT)
# =============================================================================


class TripSegment(BaseModel):
    """
    A single booking segment (flight, hotel, or activity tile).

    Represents a booked or planned item in the trip.
    """

    type: Literal["flight", "hotel", "activity"]
    tile_id: Optional[str] = None  # Reference to Tile.id if booked
    params: Dict[str, Any] = Field(default_factory=dict)
    # params may include: dates, location, constraints, preferences


class ItineraryBlock(BaseModel):
    """
    A content block for the itinerary, generated by Vertical Specialist.

    This is the "Guide" content that makes the trip interesting,
    not just valid bookings.
    """

    day: int
    title: str
    description: str
    type: Literal["activity", "meal", "transport", "rest", "experience"]
    image_url: Optional[str] = None
    duration_hours: Optional[float] = None
    location: Optional[str] = None
    # Specialist metadata
    source_specialist: Optional[str] = None  # "diving", "hiking", etc.
    skill_level: Optional[str] = None  # "beginner", "intermediate", "advanced"
    safety_notes: Optional[str] = None
    # Tile reference if bookable
    tile_id: Optional[str] = None


class SpecialistConstraint(BaseModel):
    """
    A constraint injected by the Vertical Specialist.

    The Architect MUST respect these when calling TileService.
    """

    type: Literal["temporal", "safety", "equipment", "certification", "budget"]
    rule: str  # e.g., "min_24h_buffer_after_dive"
    applies_to: Optional[str] = None  # "flights", "activities", etc.
    parameters: Dict[str, Any] = Field(default_factory=dict)
    reason: Optional[str] = None  # Human-readable explanation


class TripPlan(BaseModel):
    """
    The Single Source of Truth (SSoT) for the trip.

    Managed exclusively by the Trip Architect.
    """

    # Core fields (required for booking)
    destination: Optional[str] = None
    destinations: List[str] = Field(default_factory=list)  # For multi-city
    origin: Optional[str] = None
    start_date: Optional[str] = None
    end_date: Optional[str] = None

    # Traveler info
    travelers: int = 1
    adults: int = 1
    children: int = 0

    # Budget
    budget: Optional[float] = None
    currency: str = "USD"

    # Plan status
    status: Literal["draft", "planning", "ready", "booked"] = "draft"

    # Booked segments
    segments: List[TripSegment] = Field(default_factory=list)

    # Specialist-generated content
    itinerary_blocks: List[ItineraryBlock] = Field(default_factory=list)

    # Constraints from Specialist
    constraints: List[SpecialistConstraint] = Field(default_factory=list)

    # Trip metadata
    trip_type: Optional[str] = None  # "diving", "hiking", "city_break", etc.
    vibe: Optional[str] = None  # "adventure", "relaxation", "cultural", etc.


# =============================================================================
# Specialist Output Models
# =============================================================================


class SpecialistOutput(BaseModel):
    """
    Output from the Vertical Specialist node.

    Contains BOTH constraints AND content (the key insight from planning).
    """

    # Safety/logic constraints
    constraints: List[SpecialistConstraint] = Field(default_factory=list)

    # Content blocks (S1/S2 strategy content)
    content_blocks: List[ItineraryBlock] = Field(default_factory=list)

    # Critique of current plan (if any)
    critique: Optional[str] = None

    # Enhancements to suggest
    enhancements: List[str] = Field(default_factory=list)


# =============================================================================
# UI Event Models
# =============================================================================


class UIEvent(BaseModel):
    """
    An event to trigger frontend UI changes.

    Preserves the "Multi-Agent" feel in the UI.
    """

    type: Literal[
        "SPECIALIST_ACTIVE",
        "SPECIALIST_DONE",
        "TILES_LOADING",
        "TILES_READY",
        "CONSTRAINT_VIOLATED",
        "MISSING_FIELDS",
        "PLAN_READY",
    ]
    agent_id: Optional[str] = None  # "architect", "diving", "hiking", etc.
    data: Dict[str, Any] = Field(default_factory=dict)


class MissingFieldsResponse(BaseModel):
    """
    Structured response for missing required fields.

    Triggers the Setup Modal in the frontend.
    """

    type: Literal["missing_fields"] = "missing_fields"
    fields: List[str]  # ["destination", "dates"]
    message: str  # "Let's finish setting up your trip!"


# =============================================================================
# Synthesizer Output Models
# =============================================================================


class SynthesizerOutput(BaseModel):
    """
    Output from the Synthesizer node.

    Includes suggested replies for UX continuity.
    """

    message: str
    suggested_replies: List[str] = Field(
        default_factory=lambda: ["Add activities", "Change dates", "Show options"]
    )
    ui_events: List[UIEvent] = Field(default_factory=list)


# =============================================================================
# V2 Graph State
# =============================================================================


class GraphStateV2(BaseModel):
    """
    Unified state for the 6-node architecture.

    Key differences from V1:
    - TripPlan is the SSoT (not fragmented trip_inputs)
    - active_specialist triggers dynamic Specialist node
    - constraints are first-class citizens
    - ui_events preserve frontend UX
    """

    # Chat history
    messages: List[BaseMessage] = Field(default_factory=list)

    # The Single Source of Truth
    trip_plan: TripPlan = Field(default_factory=TripPlan)

    # Intent classification (from Router)
    intent: Optional[Literal["general", "booking", "specialist"]] = None

    # Specialist activation
    active_specialist: Optional[str] = None  # "diving", "hiking", "skiing", etc.
    active_agent_id: Optional[str] = None  # For UI display

    # Tile inventory (from TileService)
    tiles: Dict[str, List[Dict[str, Any]]] = Field(default_factory=dict)
    # Structure: {"flights": [...], "hotels": [...], "activities": [...]}

    # Constraint violations (from ConstraintGuard)
    constraints_violated: List[str] = Field(default_factory=list)

    # UI events for frontend
    ui_events: List[str] = Field(default_factory=list)

    # Response state
    last_summary: Optional[str] = None
    suggested_replies: List[str] = Field(default_factory=list)

    # Metadata for debugging/tracking
    metadata: Dict[str, Any] = Field(default_factory=dict)

    model_config = {"arbitrary_types_allowed": True}


# =============================================================================
# Helper Functions
# =============================================================================


def trip_plan_is_ready(plan: TripPlan) -> bool:
    """Check if trip plan has all required fields for booking."""
    return bool((plan.destination or plan.destinations) and plan.start_date)


def get_missing_fields(plan: TripPlan) -> List[str]:
    """Get list of missing required fields."""
    missing = []
    if not plan.destination and not plan.destinations:
        missing.append("destination")
    if not plan.start_date:
        missing.append("dates")
    return missing


def create_missing_fields_response(plan: TripPlan) -> Optional[MissingFieldsResponse]:
    """Create structured missing fields response for frontend modal."""
    missing = get_missing_fields(plan)
    if missing:
        return MissingFieldsResponse(fields=missing, message="Let's finish setting up your trip!")
    return None
