"""
V2 State Schemas - Simplified "Core + Specialist" Architecture.

This module defines the state models for the 7-node architecture:
- TripPlan: Single Source of Truth for the trip
- TripSegment: Individual booking segment (flight/hotel/activity)
- ItineraryBlock: Specialist-generated content (activities, experiences)
- SpecialistConstraint: Domain constraints from Vertical Specialist
- GraphState: Unified state for the new architecture

Key Principle: Architect sees the whole picture.
"""

from enum import Enum
from typing import Any, Dict, List, Literal, Optional

from langchain_core.messages import BaseMessage
from pydantic import BaseModel, Field

# =============================================================================
# Constraint Severity Enum
# =============================================================================


class ConstraintSeverity(str, Enum):
    """
    Constraint priority levels for multi-specialist conflict resolution.

    BLOCKING: Safety/Legal constraints - always wins (e.g., 24h no-fly)
    STRONG: Optimization constraints - negotiates (e.g., best weather)
    SOFT: Preference constraints - defers (e.g., scenic route)
    """

    BLOCKING = "blocking"
    STRONG = "strong"
    SOFT = "soft"


# =============================================================================
# Trip Plan Models (SSoT)
# =============================================================================


class TripSegment(BaseModel):
    """
    A single booking segment (flight, hotel, or activity tile).

    Represents a booked or planned item in the trip.
    """

    type: Literal["flight", "hotel", "activity"]
    tile_id: Optional[str] = None  # Reference to Tile.id if booked
    params: Dict[str, Any] = Field(default_factory=dict)
    # params may include: dates, location, constraints, preferences


class Activity(BaseModel):
    """
    Rich activity model with topic-specific optional fields.
    Generated by LLM specialists via generate_specialist_output_llm().

    Topic-specific fields are populated when relevant:
    - Diving: depth_meters, certification_required
    - Hiking: elevation_meters, distance_km
    - Skiing: vertical_meters, run_difficulty
    """

    title: str
    description: str = ""
    location: Optional[str] = None
    duration_hours: float = 3.0
    difficulty: Literal["beginner", "intermediate", "advanced"] = "beginner"

    # Scheduling hints (LLM can suggest)
    day: Optional[int] = None
    period: Optional[Literal["morning", "afternoon", "evening"]] = None

    # Display
    image_url: Optional[str] = None
    logic_hook: Optional[str] = None  # Pro tip for UI

    # === TOPIC-SPECIFIC OPTIONAL FIELDS ===
    # Diving
    depth_meters: Optional[int] = None
    certification_required: Optional[str] = None  # "Open Water", "Advanced", etc.

    # Hiking
    elevation_meters: Optional[int] = None
    distance_km: Optional[float] = None
    trail_type: Optional[str] = None  # "loop", "out-and-back", "point-to-point"

    # Skiing
    vertical_meters: Optional[int] = None
    run_difficulty: Optional[str] = None  # "green", "blue", "red", "black"

    # Generic extension point for future topics
    topic_metadata: Dict[str, Any] = Field(default_factory=dict)


class ItineraryBlock(BaseModel):
    """
    A content block for the itinerary, generated by Vertical Specialist.

    This is the "Guide" content that makes the trip interesting,
    not just valid bookings.
    """

    day: int
    title: str
    description: str
    type: Literal["activity", "meal", "transport", "rest", "experience", "buffer"]
    image_url: Optional[str] = None
    duration_hours: Optional[float] = None
    location: Optional[str] = None
    coordinates: Optional[List[float]] = None  # [lng, lat] for Mapbox - Bridge Mode map POIs
    # Specialist metadata
    source_specialist: Optional[str] = None  # "diving", "hiking", etc.
    skill_level: Optional[str] = None  # "beginner", "intermediate", "advanced"
    safety_notes: Optional[str] = None
    logic_hook: Optional[str] = None  # "Why this matters" tip for UI (e.g., "Indoor - Summer safe")
    # Tile reference if bookable
    tile_id: Optional[str] = None
    # Buffer/Safety block fields (for No-Fly intervals, acclimatization, etc.)
    is_buffer: bool = False
    buffer_type: Optional[
        Literal["no_fly", "rest_day", "acclimatization", "arrival", "departure"]
    ] = None
    buffer_reason: Optional[str] = (
        None  # e.g., "PADI Standard - 24h surface interval before flying"
    )


class SpecialistConstraint(BaseModel):
    """
    A constraint injected by the Vertical Specialist.

    The Architect MUST respect these when calling TileService.
    Constraints have severity levels for multi-specialist conflict resolution.
    """

    # Unique constraint identifier (for LLM-generated constraints)
    constraint_id: str = Field(
        default="",
        description="Unique snake_case ID: no_fly_24h, altitude_buffer, certification_required",
    )

    type: Literal["temporal", "safety", "equipment", "certification", "budget"]
    rule: str  # e.g., "min_24h_buffer_after_dive"
    severity: ConstraintSeverity = ConstraintSeverity.STRONG  # Priority for conflicts
    applies_to: Optional[str] = None  # DEPRECATED: Use applies_to_categories
    applies_to_categories: List[str] = Field(
        default_factory=list,
        description="Activity categories this constraint applies to (cross-domain)",
    )
    parameters: Dict[str, Any] = Field(default_factory=dict)
    reason: Optional[str] = None  # Human-readable explanation

    # UI display fields (for constraint visualization)
    label: Optional[str] = None  # Short display label e.g., "24h no-fly buffer"
    icon: Optional[str] = None  # Emoji icon e.g., "🚫"
    buffer_hours: Optional[int] = None  # For temporal constraints e.g., 24


class TripPlan(BaseModel):
    """
    The Single Source of Truth (SSoT) for the trip.

    Managed exclusively by the Trip Architect.
    """

    # Core fields (required for booking)
    destination: Optional[str] = None
    origin: Optional[str] = None
    start_date: Optional[str] = None
    end_date: Optional[str] = None

    # Traveler info
    travelers: int = 1
    adults: int = 1
    children: int = 0

    # Budget
    budget: Optional[float] = None
    currency: str = "USD"

    # Plan status
    status: Literal["draft", "planning", "ready", "booked"] = "draft"

    # Booked segments
    segments: List[TripSegment] = Field(default_factory=list)

    # Specialist-generated content
    itinerary_blocks: List[ItineraryBlock] = Field(default_factory=list)

    # Constraints from Specialist
    constraints: List[SpecialistConstraint] = Field(default_factory=list)

    # Trip metadata
    trip_type: Optional[str] = None  # "diving", "hiking", "city_break", etc.
    vibe: Optional[str] = None  # "adventure", "relaxation", "cultural", etc.


# =============================================================================
# Specialist Output Models
# =============================================================================


class SpecialistOutput(BaseModel):
    """
    Output from the Vertical Specialist node.

    Contains BOTH constraints AND content (the key insight from planning).
    """

    # Feasibility assessment (checked BEFORE generating content)
    feasibility_status: Literal["feasible", "caveat", "infeasible"] = "feasible"
    feasibility_reason: Optional[str] = None  # e.g., "Indoor skiing only (SnowWorld)"
    alternative_suggestion: Optional[str] = None  # e.g., "Try Winterberg (3.5h drive)"

    # Safety/logic constraints
    constraints: List[SpecialistConstraint] = Field(default_factory=list)

    # Content blocks (S1/S2 strategy content)
    content_blocks: List[ItineraryBlock] = Field(default_factory=list)

    # Critique of current plan (if any)
    critique: Optional[str] = None

    # Enhancements to suggest
    enhancements: List[str] = Field(default_factory=list)


# =============================================================================
# UI Event Models
# =============================================================================


class UIEvent(BaseModel):
    """
    An event to trigger frontend UI changes.

    Preserves the "Multi-Agent" feel in the UI.
    """

    type: Literal[
        "SPECIALIST_ACTIVE",
        "SPECIALIST_DONE",
        "TILES_LOADING",
        "TILES_READY",
        "CONSTRAINT_VIOLATED",
        "MISSING_FIELDS",
        "PLAN_READY",
        "PLAN_UPDATE",
    ]
    agent_id: Optional[str] = None  # "architect", "diving", "hiking", etc.
    data: Dict[str, Any] = Field(default_factory=dict)


class MissingFieldsResponse(BaseModel):
    """
    Structured response for missing required fields.

    Triggers the Setup Modal in the frontend.
    """

    type: Literal["missing_fields"] = "missing_fields"
    fields: List[str]  # ["destination", "dates"]
    message: str  # "Let's finish setting up your trip!"


# =============================================================================
# Synthesizer Output Models
# =============================================================================


class SynthesizerOutput(BaseModel):
    """
    Output from the Synthesizer node.

    Includes suggested replies for UX continuity.
    """

    message: str
    suggested_replies: List[str] = Field(
        default_factory=lambda: ["Add activities", "Change dates", "Show options"]
    )
    ui_events: List[UIEvent] = Field(default_factory=list)


# =============================================================================
# LLM Extraction Schema
# =============================================================================


class ExtractedTripFields(BaseModel):
    """
    Structured extraction from user message via LLM.

    Used by TripArchitect to extract trip fields without regex.
    GPT-4o-mini resolves relative dates (e.g., "next Friday") to ISO format.
    """

    destination: Optional[str] = Field(None, description="Destination city/country")
    origin: Optional[str] = Field(None, description="Origin city for flights")
    start_date: Optional[str] = Field(None, description="Start date in YYYY-MM-DD format")
    end_date: Optional[str] = Field(None, description="End date in YYYY-MM-DD format")
    duration_days: Optional[int] = Field(
        None, description="Trip duration if mentioned (e.g., 'for a week' = 7)"
    )
    adults: Optional[int] = Field(None, description="Number of adults")
    children: Optional[int] = Field(None, description="Number of children")
    budget: Optional[float] = Field(None, description="Budget amount in USD (e.g., '2k' = 2000)")
    budget_tier: Optional[str] = Field(
        None, description="Budget tier if qualitative: budget/mid-range/luxury"
    )
    trip_type: Optional[str] = Field(
        None, description="Trip type: diving/hiking/skiing/beach/city/etc"
    )

    model_config = {
        "json_schema_extra": {
            "example": {
                "destination": "Bali",
                "origin": "London",
                "start_date": "2026-02-15",
                "end_date": "2026-02-22",
                "adults": 2,
                "budget": 3000,
            }
        }
    }


class ExtractedSettingsFields(BaseModel):
    """
    Structured extraction for booking toggles and settings from user message.

    Used by TripArchitect to extract settings changes via LLM.
    All fields are Optional - only extract what the user explicitly mentions.
    """

    # Booking type toggles (tri-state: "off", "suggested", "on")
    flights_toggle: Optional[Literal["off", "suggested", "on"]] = Field(
        None, description="Toggle for flight search: off/suggested/on"
    )
    hotels_toggle: Optional[Literal["off", "suggested", "on"]] = Field(
        None, description="Toggle for hotel search: off/suggested/on"
    )
    activities_toggle: Optional[Literal["off", "suggested", "on"]] = Field(
        None, description="Toggle for activity search: off/suggested/on"
    )
    ground_transport_toggle: Optional[Literal["off", "suggested", "on"]] = Field(
        None, description="Toggle for ground transport: off/suggested/on"
    )

    # Flight settings
    flight_direct_only: Optional[bool] = Field(
        None, description="Only show direct flights (no layovers)"
    )
    flight_cabin_class: Optional[Literal["economy", "premium_economy", "business", "first"]] = (
        Field(None, description="Cabin class preference")
    )
    flight_round_trip: Optional[bool] = Field(
        None, description="Round trip (true) or one-way (false)"
    )

    # Hotel settings
    hotel_min_stars: Optional[int] = Field(
        None, ge=0, le=5, description="Minimum hotel star rating (0-5)"
    )

    # Activity settings
    activity_skill_level: Optional[Literal["beginner", "intermediate", "advanced"]] = Field(
        None, description="Activity skill level filter"
    )

    model_config = {
        "json_schema_extra": {
            "example": {
                "flights_toggle": "off",
                "hotel_min_stars": 5,
                "flight_cabin_class": "business",
            }
        }
    }


# =============================================================================
# V2 Graph State
# =============================================================================


class GraphState(BaseModel):
    """
    Unified state for the 7-node architecture.

    Key differences from V1:
    - TripPlan is the SSoT (not fragmented trip_inputs)
    - active_specialist triggers dynamic Specialist node
    - constraints are first-class citizens
    - ui_events preserve frontend UX
    """

    # Chat history
    messages: List[BaseMessage] = Field(default_factory=list)

    # The Single Source of Truth
    trip_plan: TripPlan = Field(default_factory=TripPlan)

    # Intent classification (from Router)
    intent: Optional[Literal["general", "booking", "specialist"]] = None

    # Specialist activation
    active_specialist: Optional[str] = None  # "diving", "hiking", "skiing", etc.
    active_agent_id: Optional[str] = None  # For UI display

    # Multi-specialist support: queue of specialists to process
    pending_specialists: List[str] = Field(default_factory=list)

    # Tile inventory (from TileService)
    tiles: Dict[str, List[Dict[str, Any]]] = Field(default_factory=dict)
    # Structure: {"flights": [...], "hotels": [...], "activities": [...]}

    # Constraint violations (from ConstraintGuard)
    constraints_violated: List[str] = Field(default_factory=list)

    # Auto-fix loop retry counter (Guard → Architect)
    guard_retry_count: int = 0

    # UI events for frontend
    ui_events: List[str] = Field(default_factory=list)

    # Response state
    last_summary: Optional[str] = None
    suggested_replies: List[str] = Field(default_factory=list)

    # Metadata for debugging/tracking
    metadata: Dict[str, Any] = Field(default_factory=dict)

    # TRACKING: Detect input changes to trigger re-planning
    last_constraint_hash: Optional[str] = None

    model_config = {"arbitrary_types_allowed": True}


# =============================================================================
# Helper Functions
# =============================================================================


def trip_plan_is_ready(plan: TripPlan) -> bool:
    """Check if trip plan has all required fields for booking."""
    return bool(plan.destination and plan.start_date)


def get_missing_fields(plan: TripPlan) -> List[str]:
    """Get list of missing required fields."""
    missing = []
    if not plan.destination:
        missing.append("destination")
    if not plan.start_date:
        missing.append("dates")
    return missing


def create_missing_fields_response(plan: TripPlan) -> Optional[MissingFieldsResponse]:
    """Create structured missing fields response for frontend modal."""
    missing = get_missing_fields(plan)
    if missing:
        return MissingFieldsResponse(fields=missing, message="Let's finish setting up your trip!")
    return None
