/* eslint no-unused-vars: ["error", { "args": "none" }] */
'use client';

import { useCallback, useMemo, useRef, useState } from 'react';

import { fetchWithRetry } from '@/lib/api';
import { debugLog } from '@/lib/debug';
import type { DocumentBranch, PlanDocumentResponse } from '@/types/document';
import type { Tile, TileSelection } from '@/types/tile';

import { EMPTY_TILE_SELECTION, selectionsToTileSelection } from './useTileSelection';

// ─────────────────────────────────────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Override options when selecting a branch.
 * Used during session hydration to provide additional context.
 */
type BranchSelectionOverrides = {
  /** Pre-resolved branch object (avoids lookup in branches array) */
  branch?: DocumentBranch;
  /** Trip context ID for the session */
  tripContextId?: number | null;
  /** Custom error message to show if tile fetch fails */
  errorMessageOverride?: string;
};

/**
 * Options for the useBranchState hook.
 */
interface UseBranchStateOptions {
  /**
   * Toast notification callback for error messages.
   */
  onToast: (message: string) => void;
}

/**
 * Return type for the useBranchState hook.
 */
interface UseBranchStateReturn {
  // ─────────────────────────────────────────────────────────────────────────
  // State
  // ─────────────────────────────────────────────────────────────────────────

  /**
   * All branches (trip suggestions) in the current session.
   * Each branch represents a different trip option generated by the AI.
   */
  branches: DocumentBranch[];

  /**
   * The currently selected branch ID.
   * null if no branch is selected (e.g., before any suggestions are generated).
   */
  selectedBranchId: string | null;

  /**
   * Map of tile IDs to tile objects.
   * Contains all tiles across all branches for quick lookup.
   *
   * @internal Exposed for debugging. UI should use `tiles` computed value instead.
   */
  tilesMap: Record<string, Tile>;

  /**
   * The branch ID for which tiles are currently loaded in tilesMap.
   * null if tiles are being fetched or not yet loaded.
   *
   * May differ from selectedBranchId during branch switching while tiles load.
   */
  tilesBranchId: string | null;

  /**
   * Selection state for each branch, indexed by branch ID.
   * Each branch maintains independent selections that persist when switching branches.
   */
  branchSelections: Record<string, TileSelection>;

  // ─────────────────────────────────────────────────────────────────────────
  // Computed
  // ─────────────────────────────────────────────────────────────────────────

  /**
   * The currently selected branch object.
   * null if no branch is selected.
   */
  selectedBranch: DocumentBranch | null;

  /**
   * Array of tile objects for the selected branch.
   * Combines stays, flights, and activities into a single array.
   * Empty if no branch is selected or tiles aren't loaded.
   */
  tiles: Tile[];

  /**
   * Whether any branches have been generated.
   * Used to determine UI state (show landing vs results view).
   */
  hasBranchesReady: boolean;

  // ─────────────────────────────────────────────────────────────────────────
  // Setters (for external state management)
  // ─────────────────────────────────────────────────────────────────────────

  /** Direct setter for branches state */
  setBranches: React.Dispatch<React.SetStateAction<DocumentBranch[]>>;

  /** Direct setter for selected branch ID */
  setSelectedBranchId: React.Dispatch<React.SetStateAction<string | null>>;

  /** Direct setter for tiles map */
  setTilesMap: React.Dispatch<React.SetStateAction<Record<string, Tile>>>;

  /** Direct setter for tiles branch ID */
  setTilesBranchId: React.Dispatch<React.SetStateAction<string | null>>;

  /** Direct setter for branch selections */
  setBranchSelections: React.Dispatch<React.SetStateAction<Record<string, TileSelection>>>;

  // ─────────────────────────────────────────────────────────────────────────
  // Actions
  // ─────────────────────────────────────────────────────────────────────────

  /**
   * Selects a branch and fetches its tiles from the API.
   *
   * @param branchId - The ID of the branch to select
   * @param overrides - Optional overrides for error handling and branch lookup
   *
   * @remarks
   * This handler:
   * 1. Aborts any in-flight tile fetch
   * 2. Updates selectedBranchId immediately for UI feedback
   * 3. Clears tilesBranchId to show loading state
   * 4. Fetches tiles from the API
   * 5. Updates state with fetched tiles
   *
   * Tile fetches are abortable - if user switches branches quickly,
   * previous requests are cancelled to avoid race conditions.
   */
  handleBranchSelect: (branchId: string, overrides?: BranchSelectionOverrides) => Promise<void>;

  /**
   * Aborts any in-flight tile fetch request.
   * Called internally when switching branches or clearing context.
   */
  abortTilesFetch: () => void;
}

// ─────────────────────────────────────────────────────────────────────────────
// Hook
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Hook for managing branch state and tile fetching.
 *
 * This is the core state management hook for the branch manager.
 * It handles:
 * - Branch and tile state storage
 * - Computed values (selected branch, tiles array)
 * - Branch selection with tile fetching
 * - Request abort handling for rapid branch switching
 *
 * @param options - Configuration options for the hook
 * @returns Branch state, computed values, and actions
 *
 * @remarks
 * This hook owns the primary state but exposes setters for external updates.
 * This allows other hooks (like useSessionHydration) to populate state
 * without creating circular dependencies.
 *
 * The tilesMap is a denormalized cache of all tiles. When a branch is selected,
 * its tiles are fetched and merged into this map. This allows quick tile lookups
 * and preserves tiles from previously viewed branches.
 *
 * TODO: Consider adding tile cache eviction for very long sessions.
 * TODO: Consider adding optimistic tile loading (prefetch tiles for nearby branches).
 *
 * @example
 * ```tsx
 * const {
 *   branches,
 *   selectedBranch,
 *   tiles,
 *   handleBranchSelect,
 * } = useBranchState({ onToast });
 *
 * // Select a branch (fetches tiles automatically)
 * await handleBranchSelect(branchId);
 *
 * // Render tiles
 * tiles.map(tile => <TileCard tile={tile} />)
 * ```
 */
export function useBranchState(options: UseBranchStateOptions): UseBranchStateReturn {
  const { onToast } = options;

  // ─────────────────────────────────────────────────────────────────────────
  // State
  // ─────────────────────────────────────────────────────────────────────────

  const [branches, setBranches] = useState<DocumentBranch[]>([]);
  const [selectedBranchId, setSelectedBranchId] = useState<string | null>(null);
  const [tilesMap, setTilesMap] = useState<Record<string, Tile>>({});
  const [tilesBranchId, setTilesBranchId] = useState<string | null>(null);
  const [branchSelections, setBranchSelections] = useState<Record<string, TileSelection>>({});

  // ─────────────────────────────────────────────────────────────────────────
  // Refs
  // ─────────────────────────────────────────────────────────────────────────

  /**
   * AbortController for the current tile fetch request.
   * Used to cancel in-flight requests when switching branches quickly.
   */
  const tilesFetchControllerRef = useRef<AbortController | null>(null);

  // ─────────────────────────────────────────────────────────────────────────
  // Computed Values
  // ─────────────────────────────────────────────────────────────────────────

  /**
   * The currently selected branch object.
   * Memoized to avoid unnecessary re-renders when branches array changes
   * but the selected branch remains the same.
   */
  const selectedBranch = useMemo(
    () => branches.find((branch) => branch.id === selectedBranchId) ?? null,
    [branches, selectedBranchId]
  );

  /**
   * Array of tile objects for the selected branch.
   * Combines all tile categories (stays, flights, activities) into one array.
   *
   * Only includes tiles that exist in tilesMap - missing tiles are filtered out.
   * This can happen if tiles haven't loaded yet or if there's a data inconsistency.
   */
  const tiles = useMemo(() => {
    if (!selectedBranch) return [];
    const tileIds = [
      ...selectedBranch.tiles.stays,
      ...selectedBranch.tiles.flights,
      ...selectedBranch.tiles.activities,
    ];
    return tileIds
      .map((id) => tilesMap[id])
      .filter((tile): tile is Tile => tile !== undefined);
  }, [selectedBranch, tilesMap]);

  const hasBranchesReady = branches.length > 0;

  // ─────────────────────────────────────────────────────────────────────────
  // Actions
  // ─────────────────────────────────────────────────────────────────────────

  /**
   * Aborts any in-flight tile fetch request.
   * Safe to call even if no request is in progress.
   */
  const abortTilesFetch = useCallback(() => {
    if (tilesFetchControllerRef.current) {
      tilesFetchControllerRef.current.abort();
      tilesFetchControllerRef.current = null;
    }
  }, []);

  /**
   * Handles branch selection with tile fetching.
   *
   * The flow:
   * 1. Abort any existing fetch to prevent race conditions
   * 2. Update UI state immediately (selectedBranchId)
   * 3. Clear tilesBranchId to show loading state
   * 4. Initialize empty selection for new branch if needed
   * 5. Fetch tiles from API
   * 6. Update state with response
   *
   * Error handling shows a toast but doesn't revert state -
   * user can retry by selecting the branch again.
   */
  const handleBranchSelect = useCallback(
    async (branchId: string, overrides?: BranchSelectionOverrides) => {
      // Abort any in-flight request
      abortTilesFetch();

      // Create new abort controller for this request
      const controller = new AbortController();
      tilesFetchControllerRef.current = controller;

      // Check if we're switching branches
      const branchChanged = branchId !== selectedBranchId;

      // Update UI state immediately
      setSelectedBranchId(branchId);
      setTilesBranchId(null); // Mark tiles as loading

      // Initialize empty selection for new branch if needed
      if (branchChanged) {
        setBranchSelections((prev) => {
          if (prev[branchId]) return prev;
          return { ...prev, [branchId]: EMPTY_TILE_SELECTION };
        });
      }

      // Find the branch (use override if provided, otherwise lookup)
      const branch = overrides?.branch ?? branches.find((b) => b.id === branchId);
      if (!branch) return;

      const errorMessageOverride = overrides?.errorMessageOverride;

      try {
        // Use fetchWithRetry for automatic retry on transient errors (network timeouts, 503s)
        const res = await fetchWithRetry(
          `/api/document/tiles/${encodeURIComponent(branchId)}`,
          {
            method: 'POST',
            signal: controller.signal,
          },
          {
            maxRetries: 3,
            baseDelay: 1000,
            onRetry: (attempt, error) => {
              debugLog(`Tile fetch retry ${attempt}:`, error);
            },
          }
        );

        if (!res.ok) {
          debugLog('Failed to fetch tiles for branch', res.status);
          if (res.status === 429) {
            onToast('Rate limit reached. Please wait a moment and try again.');
          } else {
            onToast(
              errorMessageOverride ??
                'Unable to refresh options for that suggestion. Please try again.'
            );
          }
          return;
        }

        const data: PlanDocumentResponse = await res.json();

        // Check if request was aborted while waiting for response
        if (controller.signal.aborted) return;

        // Update state with fetched data
        setBranches(data.document.branches);
        setTilesMap(data.document.tiles);
        setTilesBranchId(branchId);

        // Update selections from server response
        const newSelections: Record<string, TileSelection> = {};
        for (const b of data.document.branches) {
          newSelections[b.id] = selectionsToTileSelection(b.selections, data.document.tiles);
        }
        setBranchSelections(newSelections);
      } catch (error) {
        // Ignore abort errors (expected when switching branches quickly)
        if ((error as DOMException).name === 'AbortError') return;

        console.error('Failed to fetch tiles for branch', error);
        onToast(
          errorMessageOverride ??
            'Unable to refresh options for that suggestion. Please try again.'
        );
      } finally {
        // Clean up controller reference if this is still the active request
        if (tilesFetchControllerRef.current === controller) {
          tilesFetchControllerRef.current = null;
        }
      }
    },
    [abortTilesFetch, branches, selectedBranchId, onToast]
  );

  return {
    // State
    branches,
    selectedBranchId,
    tilesMap,
    tilesBranchId,
    branchSelections,

    // Computed
    selectedBranch,
    tiles,
    hasBranchesReady,

    // Setters
    setBranches,
    setSelectedBranchId,
    setTilesMap,
    setTilesBranchId,
    setBranchSelections,

    // Actions
    handleBranchSelect,
    abortTilesFetch,
  };
}
