"""
VerticalSpecialist Node - LLM (Expert) domain specialist.

This is the "Diving Agent" / "Hiking Agent" in the UI.
Key insight: Returns BOTH constraints AND content.

Responsibilities:
- Inject domain constraints (e.g., "Don't fly 24h after diving")
- Generate content blocks (e.g., "Day 2: USAT Liberty Wreck")
- Critique current plan from domain expertise perspective
- Suggest enhancements

Flow: Router → Specialist → Architect
The Specialist runs BEFORE the Architect calls tools.
"""

import asyncio
import json
import os
import time
from typing import Any, Dict, List, Optional, Tuple

from pydantic import BaseModel

from app.config import settings
from app.placeholders import get_activity_image
from app.planner.services.section_builder import (
    build_specialist_section,
    mark_topic_executed,
    upsert_section,
)
from app.planner.specialist_registry import (
    TIER1_SPECIALIST_NAMES,
    load_prompt,
)
from app.planner.specialist_registry import (
    get as get_specialist_config,
)
from app.planner.state import (
    ConstraintSeverity,
    GraphState,
    ItineraryBlock,
    SpecialistConstraint,
    SpecialistOutput,
    get_trip_settings,
)

# =============================================================================
# LLM Specialist Output Schema (for structured output)
# =============================================================================


class LLMActivity(BaseModel):
    """Activity generated by LLM specialist."""

    title: str
    description: str = ""
    location: Optional[str] = None
    duration_hours: float = 3.0
    difficulty: str = "beginner"  # beginner, intermediate, advanced
    # Topic-specific
    depth_meters: Optional[int] = None
    elevation_meters: Optional[int] = None
    distance_km: Optional[float] = None
    certification_required: Optional[str] = None
    vertical_meters: Optional[int] = None
    logic_hook: Optional[str] = None
    # LLM-generated coordinates (replaces hardcoded ACTIVITY_COORDINATES)
    lat: Optional[float] = None
    lng: Optional[float] = None


class LLMConstraint(BaseModel):
    """Constraint generated by LLM specialist."""

    constraint_id: str  # e.g., "no_fly_24h"
    constraint_type: str = "blocking"  # blocking, strong, soft
    applies_to_categories: List[str] = []
    buffer_hours: Optional[int] = None
    reason: str = ""
    label: Optional[str] = None
    icon: Optional[str] = None


class LLMSpecialistOutput(BaseModel):
    """Complete output from LLM specialist call."""

    feasibility_status: str = "feasible"  # feasible, infeasible, conditional
    feasibility_reason: Optional[str] = None
    activities: List[LLMActivity] = []
    constraints: List[LLMConstraint] = []


def _record_specialist_latency_metric(
    state: GraphState,
    topic: str,
    source: str,
    elapsed_ms: int,
    reason: str = "none",
) -> None:
    from app.debug_utils import _debug_log

    metrics = state.metadata.get("specialist_latency_metrics", {}) or {}
    metrics[topic] = {
        "source": source,
        "elapsed_ms": elapsed_ms,
        "reason": reason,
    }
    state.metadata["specialist_latency_metrics"] = metrics
    _debug_log(
        "[VERIFY][LLM_LATENCY] "
        f"component=specialist topic={topic} source={source} "
        f"elapsed_ms={elapsed_ms} reason={reason}"
    )


# =============================================================================
# LLM Specialist Generation
# =============================================================================


async def generate_all_specialists_parallel(
    topics: List[str],
    destination: str,
    trip_plan: Any,
    db: Optional[Any] = None,  # AsyncSession for persistent caching
    skill_level: Optional[str] = None,  # User skill from activity_settings
    day_preferences: Optional[Dict[str, int]] = None,  # Per-topic target counts
) -> Dict[str, Optional[LLMSpecialistOutput]]:
    """
    Run all specialist LLM calls in parallel.

    Performance optimization: 8-12s sequential → 4-6s parallel.
    Returns dict mapping topic -> LLMSpecialistOutput (or None on failure).

    Args:
        db: Optional AsyncSession for L1+L2 persistent caching.
            If provided, results are cached to PostgreSQL (7-day TTL).
        day_preferences: Per-topic day allocation from user stepper (e.g. {"diving": 5}).
            Busts cache and sets LLM generation target when present.

    Note: Cache operations are done BEFORE and AFTER parallel execution to avoid
    SQLAlchemy concurrent session errors. The db session is NOT passed to parallel
    tasks - instead we do batch lookup/write with the session sequentially.
    """
    import asyncio

    from app.debug_utils import _debug_log

    if not topics:
        return {}

    _debug_log(f"[LLM_SPECIALIST] Starting PARALLEL generation for {topics}")

    output: Dict[str, Optional[LLMSpecialistOutput]] = {}
    topics_needing_llm: List[str] = []

    # =========================================================================
    # STEP 1: Batch cache lookup (sequential, single session)
    # =========================================================================
    _debug_log(
        f"[LLM_SPECIALIST] Parallel lookup: topics={topics} "
        f"dest={destination} dates={trip_plan.start_date}→{trip_plan.end_date}"
    )
    day_prefs = day_preferences or {}

    if db is not None:
        from app.services.specialist_cache import get_cached_specialist_output

        for topic in topics:
            try:
                topic_day_pref = day_prefs.get(topic)
                cached = await get_cached_specialist_output(
                    db=db,
                    topic=topic,
                    destination=destination,
                    start_date=trip_plan.start_date,
                    end_date=trip_plan.end_date,
                    skill_level=skill_level,
                    day_pref=topic_day_pref,
                )
                if cached is not None:
                    try:
                        output[topic] = LLMSpecialistOutput.model_validate(cached)
                        status = output[topic].feasibility_status
                        _debug_log(f"[LLM_SPECIALIST] CACHE HIT: {topic} ({status})")
                        continue
                    except Exception as e:
                        _debug_log(f"[LLM_SPECIALIST] Cache deserialize failed for {topic}: {e}")
            except Exception as e:
                _debug_log(f"[LLM_SPECIALIST] Cache lookup failed for {topic}: {e}")

            topics_needing_llm.append(topic)
    else:
        topics_needing_llm = list(topics)

    # =========================================================================
    # STEP 2: Parallel LLM calls (no db passed - avoid concurrent session)
    # =========================================================================
    if topics_needing_llm:
        _debug_log(f"[LLM_SPECIALIST] Cache MISS for {topics_needing_llm}, calling LLM")

        # Create tasks WITHOUT db (cache write happens after)
        tasks = [
            generate_specialist_output_llm(
                topic,
                destination,
                trip_plan,
                db=None,
                skill_level=skill_level,
                target_activities=day_prefs.get(topic),
            )
            for topic in topics_needing_llm
        ]

        try:
            results = await asyncio.wait_for(
                asyncio.gather(*tasks, return_exceptions=True),
                timeout=90.0,
            )
        except asyncio.TimeoutError:
            _debug_log("[LLM_SPECIALIST] PARALLEL timeout - cancelling remaining tasks")
            # Cancel all tasks that are still running to prevent orphaned coroutines
            for task in tasks:
                if isinstance(task, asyncio.Task) and not task.done():
                    task.cancel()
            # Wait briefly for cancellation to complete
            pending = [t for t in tasks if isinstance(t, asyncio.Task)]
            await asyncio.gather(*pending, return_exceptions=True)
            for topic in topics_needing_llm:
                output[topic] = None
            return output

        # Map results and collect for batch cache write
        llm_results: Dict[str, LLMSpecialistOutput] = {}
        for topic, result in zip(topics_needing_llm, results, strict=False):
            if isinstance(result, Exception):
                _debug_log(f"[LLM_SPECIALIST] {topic} failed in parallel: {result}")
                output[topic] = None
            else:
                output[topic] = result
                if result is not None:
                    llm_results[topic] = result

        # =====================================================================
        # STEP 3: Batch cache write (sequential, single session)
        # =====================================================================
        if db is not None and llm_results:
            from app.services.specialist_cache import set_cached_specialist_output

            for topic, llm_output in llm_results.items():
                try:
                    await set_cached_specialist_output(
                        db=db,
                        topic=topic,
                        destination=destination,
                        start_date=trip_plan.start_date,
                        end_date=trip_plan.end_date,
                        output=llm_output.model_dump(),
                        skill_level=skill_level,
                        day_pref=day_prefs.get(topic),
                    )
                except Exception as e:
                    _debug_log(f"[LLM_SPECIALIST] Cache write failed for {topic}: {e}")

    success_count = sum(1 for r in output.values() if r is not None)
    _debug_log(f"[LLM_SPECIALIST] PARALLEL complete: {success_count}/{len(topics)} succeeded")

    return output


async def generate_specialist_output_llm(
    topic: str,
    destination: str,
    trip_plan: Any,
    db: Optional[Any] = None,  # AsyncSession for persistent caching
    skill_level: Optional[str] = None,  # User skill from activity_settings
    target_activities: Optional[int] = None,  # User's day_preference for this topic
) -> Optional[LLMSpecialistOutput]:
    """
    Single LLM call generates feasibility + activities + constraints.

    Uses topic-aware system prompt from SPECIALIST_SYSTEM_PROMPTS.
    Returns None on failure (caller should use hardcoded fallback).

    Args:
        db: Optional AsyncSession for L1+L2 persistent caching.
            If provided, checks cache before LLM call and writes after success.
        target_activities: User's requested activity count from day_preferences stepper.
            When set, overrides the default min/max calculation and the LLM is
            asked to generate exactly this many activities. If the LLM returns
            fewer, repeat-session padding fills the gap.
    """
    from app.debug_utils import _debug_log

    # =========================================================================
    # CACHE CHECK: L1 (memory) → L2 (PostgreSQL)
    # =========================================================================
    if db is not None:
        try:
            from app.services.specialist_cache import get_cached_specialist_output

            cached = await get_cached_specialist_output(
                db=db,
                topic=topic,
                destination=destination,
                start_date=trip_plan.start_date,
                end_date=trip_plan.end_date,
                skill_level=skill_level,
                day_pref=target_activities,
            )

            if cached is not None:
                try:
                    output = LLMSpecialistOutput.model_validate(cached)
                    _debug_log(
                        f"[LLM_SPECIALIST] CACHE HIT: {topic} in {destination} "
                        f"(status={output.feasibility_status})"
                    )
                    return output
                except Exception as e:
                    _debug_log(f"[LLM_SPECIALIST] Cache deserialize failed: {e}")
        except Exception as e:
            _debug_log(f"[LLM_SPECIALIST] Cache lookup error: {e}")

    system_prompt = load_prompt(topic)
    if not system_prompt:
        # Unknown specialist - return None to trigger fallback
        _debug_log(f"[LLM_SPECIALIST] No system prompt for topic '{topic}', using fallback")
        return None

    # Inject user skill level so LLM generates appropriate activities
    if skill_level:
        system_prompt += (
            f"\n\nUSER SKILL LEVEL: {skill_level}. "
            "Generate activities appropriate for this level. "
            "Do NOT suggest activities above this skill level."
        )

    # Calculate trip duration
    duration_days = 5  # Default
    if trip_plan.start_date and trip_plan.end_date:
        from datetime import datetime

        try:
            start = datetime.strptime(str(trip_plan.start_date), "%Y-%m-%d")
            end = datetime.strptime(str(trip_plan.end_date), "%Y-%m-%d")
            duration_days = (end - start).days + 1
        except ValueError:
            pass

    # NOTE: JSON schema is NOT included here - it's handled by .with_structured_output()
    # OpenAI's function calling API receives the Pydantic schema directly.
    # Including redundant JSON instructions wastes ~200-500 tokens per call.

    # Calculate available activity days (excluding arrival/departure/buffers)
    available_days = max(1, duration_days - 2)

    # Scale activity count to trip length
    # Short trips (<=5 days): 2-3 activities
    # Medium trips (6-10 days): 3-5 activities
    # Long trips (11+ days): scale up to ~60% of available days, cap at 7
    if available_days <= 3:
        min_acts, max_acts = 2, 3
    elif available_days <= 8:
        min_acts, max_acts = 3, min(available_days, 5)
    else:
        min_acts = min(available_days // 3, 5)
        max_acts = min(available_days * 2 // 3, 7)

    # Override with user's day_preference if set (capped by physical available days)
    if target_activities is not None:
        capped_target = min(target_activities, available_days)
        min_acts = capped_target
        max_acts = capped_target
        _debug_log(
            f"[LLM_SPECIALIST] day_preference override: target={target_activities}, "
            f"capped={capped_target}, available_days={available_days}"
        )
    else:
        # Default cap: no explicit preference → max 3 activities
        # Prevents unbounded specialists from overstuffing the itinerary
        max_acts = min(max_acts, 3)
        min_acts = min(min_acts, max_acts)

    activity_count_instruction = (
        f"- Generate exactly {min_acts} activities"
        if min_acts == max_acts
        else f"- Generate {min_acts}-{max_acts} activities to fill available days"
    )

    user_prompt = f"""Plan {topic} activities for {destination}.

TRIP DETAILS:
- Dates: {trip_plan.start_date} to {trip_plan.end_date} ({duration_days} days)
- Travelers: {trip_plan.adults} adults, {trip_plan.children} children
- Activity days available: {available_days} (excluding arrival/departure)

REQUIREMENTS:
- Use REAL sites/trails/runs - no made-up names
{activity_count_instruction}
- Include topic-specific fields (depth_meters for diving, elevation_meters for hiking, etc.)
- Include cross-domain constraints explicitly (e.g., diving affects hiking)
- For infeasible destinations (e.g., diving in landlocked areas), \
set feasibility_status to "infeasible" with reason"""

    import time

    llm_start = time.time()
    try:
        from app.planner.llm_factory import get_llm_by_model

        llm = get_llm_by_model(settings.specialist_model, temperature=0.2)
        structured_llm = llm.with_structured_output(LLMSpecialistOutput)

        _debug_log(f"[LLM_SPECIALIST] Calling LLM for {topic} in {destination}")

        from langchain_core.messages import HumanMessage, SystemMessage

        output = await structured_llm.ainvoke(
            [
                SystemMessage(content=system_prompt),
                HumanMessage(content=user_prompt),
            ]
        )

        elapsed = time.time() - llm_start
        _debug_log(
            f"[LLM_SPECIALIST] ✅ Success for {topic} in {elapsed:.1f}s: "
            f"status={output.feasibility_status}, "
            f"activities={len(output.activities)}, constraints={len(output.constraints)}"
        )

        # =====================================================================
        # FIX C: Pad with repeat sessions if LLM returned fewer than target
        # =====================================================================
        if (
            target_activities is not None
            and output.feasibility_status == "feasible"
            and len(output.activities) < min(target_activities, available_days)
        ):
            deficit = min(target_activities, available_days) - len(output.activities)
            original_count = len(output.activities)
            if output.activities:
                for i in range(deficit):
                    source = output.activities[i % original_count]
                    repeat = source.model_copy(
                        update={"title": f"{source.title} (Session {2 + i // original_count})"}
                    )
                    output.activities.append(repeat)
                _debug_log(
                    f"[LLM_SPECIALIST] Padded {topic}: {original_count} → "
                    f"{len(output.activities)} activities (target={target_activities})"
                )

        # =====================================================================
        # CACHE WRITE: Store successful LLM output to L1 + L2
        # =====================================================================
        if db is not None:
            try:
                from app.services.specialist_cache import set_cached_specialist_output

                await set_cached_specialist_output(
                    db=db,
                    topic=topic,
                    destination=destination,
                    start_date=trip_plan.start_date,
                    end_date=trip_plan.end_date,
                    output=output.model_dump(),
                    skill_level=skill_level,
                    day_pref=target_activities,
                )
            except Exception as cache_err:
                _debug_log(f"[LLM_SPECIALIST] Cache write failed (non-fatal): {cache_err}")

        return output

    except Exception as e:
        elapsed = time.time() - llm_start
        # Log exception type to diagnose: OutputParserException = schema mismatch,
        # TimeoutError = LLM slow, ValidationError = Pydantic rejected field
        _debug_log(
            f"[LLM_SPECIALIST] ❌ FAILED for {topic} after {elapsed:.1f}s | "
            f"type={type(e).__name__} | msg={str(e)[:300]}"
        )
        return None


def _get_minimal_safety_constraints(
    topic: str, _destination: Optional[str] = None
) -> List[SpecialistConstraint]:
    """
    Get minimal hardcoded safety constraints as fallback.

    Used when LLM generation fails to ensure critical safety rules are present.
    All constraint data is driven by the specialist registry.
    """
    config = get_specialist_config(topic)
    if not config or not config.hardcoded_constraints:
        return []
    return [
        SpecialistConstraint(
            constraint_id=hc["constraint_id"],
            type=hc["type"],
            rule=hc["rule"],
            severity=ConstraintSeverity(hc["severity"]),
            applies_to_categories=hc.get("applies_to_categories", []),
            buffer_hours=hc.get("buffer_hours"),
            reason=hc.get("reason", ""),
            label=hc.get("label"),
            icon=hc.get("icon"),
        )
        for hc in config.hardcoded_constraints
    ]


def _migrate_legacy_constraints(
    constraints: List[SpecialistConstraint],
) -> List[SpecialistConstraint]:
    """
    Add constraint_id to legacy constraints from hardcoded system.

    Ensures backward compatibility when mixing old and new constraint formats.
    """
    for c in constraints:
        if not c.constraint_id:
            c.constraint_id = c.rule  # Use rule as fallback ID
    return constraints


def convert_llm_output_to_specialist_output(
    llm_output: LLMSpecialistOutput,
    topic: str,
    destination: str,
) -> SpecialistOutput:
    """
    Convert LLM output to SpecialistOutput format for the graph.

    Maps LLMActivity -> ItineraryBlock and LLMConstraint -> SpecialistConstraint.
    Images are fetched from Unsplash (activity-aware) with Unsplash placeholder fallback.
    """
    from app.services.unsplash import get_image_url_sync

    # Convert activities to ItineraryBlocks
    content_blocks: List[ItineraryBlock] = []
    for i, activity in enumerate(llm_output.activities):
        # Use Unsplash service with activity context for location-specific images
        # Variant cycles through prefetched images (0-5)
        image_url = get_image_url_sync(destination, variant=i % 6, activities=[topic])
        # Use LLM-generated coordinates ([lng, lat] Mapbox convention)
        coordinates = [activity.lng, activity.lat] if activity.lat and activity.lng else None
        content_blocks.append(
            ItineraryBlock(
                day=i + 2,  # Start from day 2 (day 1 is arrival)
                title=activity.title,
                description=activity.description,
                type="activity",
                source_specialist=topic,
                skill_level=activity.difficulty,
                logic_hook=activity.logic_hook,
                image_url=image_url,
                duration_hours=activity.duration_hours,
                location=activity.location,
                coordinates=coordinates,  # [lng, lat] for Mapbox POI pins
            )
        )

    # Convert constraints to SpecialistConstraints
    constraints: List[SpecialistConstraint] = []
    severity_map = {
        "blocking": ConstraintSeverity.BLOCKING,
        "strong": ConstraintSeverity.STRONG,
        "soft": ConstraintSeverity.SOFT,
    }
    for llm_constraint in llm_output.constraints:
        severity = severity_map.get(
            llm_constraint.constraint_type.lower(), ConstraintSeverity.STRONG
        )
        constraints.append(
            SpecialistConstraint(
                constraint_id=llm_constraint.constraint_id,
                type="safety",  # Default type
                rule=llm_constraint.constraint_id,
                severity=severity,
                applies_to_categories=llm_constraint.applies_to_categories,
                buffer_hours=llm_constraint.buffer_hours,
                reason=llm_constraint.reason,
                label=llm_constraint.label,
                icon=llm_constraint.icon,
            )
        )

    return SpecialistOutput(
        feasibility_status=llm_output.feasibility_status,
        feasibility_reason=llm_output.feasibility_reason,
        constraints=constraints,
        content_blocks=content_blocks,
    )


# =============================================================================
# LLM Feasibility Check (for unknown destinations)
# =============================================================================


class FeasibilityCheck(BaseModel):
    """LLM response for feasibility check."""

    possible: bool
    reason: str


async def _check_feasibility_llm(topic: str, destination: str) -> FeasibilityCheck:
    """
    LLM determines if activity is geographically possible.

    Uses GPT-4o-mini for fast, cheap checks (~$0.0001, ~200ms).
    Falls open on error (assumes possible) to avoid false negatives.
    """
    from app.debug_utils import _debug_log

    try:
        from app.planner.llm_factory import get_llm_by_model

        llm = get_llm_by_model(
            settings.router_model,  # Quick feasibility check
            temperature=0,
            max_tokens=100,
        )

        prompt = f"""Is {topic} activity possible in {destination}?

Rules:
- Diving requires coastline, large lakes, or dedicated dive facilities
- Skiing requires mountains with reliable snow or indoor ski facilities
- Hiking requires terrain suitable for walking trails
- Surfing requires ocean waves

Be strict. Landlocked cities cannot have diving. Alpine towns without coast cannot have diving.

Respond JSON only: {{"possible": true/false, "reason": "brief"}}"""

        response = await llm.ainvoke(prompt)
        content = response.content.strip()

        # Parse JSON response
        # Handle potential markdown code blocks
        if content.startswith("```"):
            content = content.split("```")[1]
            if content.startswith("json"):
                content = content[4:]
            content = content.strip()

        result = FeasibilityCheck(**json.loads(content))
        _debug_log(
            f"[FEASIBILITY_LLM] {topic} in {destination}: "
            f"possible={result.possible}, reason={result.reason}"
        )
        return result

    except Exception as e:
        _debug_log(f"[FEASIBILITY_LLM] Error checking {topic} in {destination}: {e}")
        # Fail open - assume possible if LLM fails
        return FeasibilityCheck(possible=True, reason="Unknown, proceeding")


# Simple async cache for feasibility checks
_feasibility_cache: Dict[str, Tuple[bool, str]] = {}
_feasibility_cache_lock = asyncio.Lock()


async def get_feasibility_llm(topic: str, destination: str) -> Tuple[bool, str]:
    """
    Cached LLM feasibility check.

    Cache key: f"{topic}:{destination}"
    Returns: (possible, reason)
    """
    cache_key = f"{topic}:{destination}"

    async with _feasibility_cache_lock:
        if cache_key in _feasibility_cache:
            return _feasibility_cache[cache_key]

    # Expensive LLM call happens outside the lock
    result = await _check_feasibility_llm(topic, destination)
    cached_result = (result.possible, result.reason)

    async with _feasibility_cache_lock:
        _feasibility_cache[cache_key] = cached_result

    return cached_result


async def check_feasibility(
    topic: str,
    destination: str,
) -> tuple:
    """
    LLM-only feasibility check, gated by registry has_geographic_constraint flag.

    Returns:
        (status, reason, alternative_suggestion) tuple where:
        - status: "feasible" | "caveat" | "infeasible"
        - reason: Human-readable explanation (or None)
        - alternative_suggestion: Suggested alternative (or None)
    """
    from app.debug_utils import _debug_log

    if not (destination or "").strip():
        return ("feasible", None, None)

    config = get_specialist_config(topic)
    if not config or not config.has_geographic_constraint:
        return ("feasible", None, None)

    # All feasibility decisions delegated to LLM
    _debug_log(f"[FEASIBILITY] LLM check for {topic} in {destination}")
    possible, reason = await get_feasibility_llm(topic, destination)

    if not possible:
        return (
            "infeasible",
            f"{topic.title()} is not available in {destination}. {reason}",
            reason,  # LLM provides alternatives in reason text
        )

    if "limited" in reason.lower():
        return ("caveat", reason, None)

    return ("feasible", None, None)


# =============================================================================
# VerticalSpecialist Class
# =============================================================================


class VerticalSpecialist:
    """
    Domain specialist that injects constraints AND content.

    NEW ARCHITECTURE (Zero-Template LLM):
    - Primary: LLM generates activities + constraints via generate_specialist_output_llm()
    - Fallback: _get_minimal_safety_constraints() provides critical safety rules

    Key insight: Returns BOTH safety constraints AND itinerary suggestions.
    Runs BEFORE Architect calls tools (Constraint Injector pattern).
    """

    def __init__(self, topic: str):
        self.topic = topic
        self.debug = bool(os.getenv("DEBUG_PLAN_MESSAGES"))
        self._cached_activity_days: int | None = None

    def get_constraints(self) -> List[SpecialistConstraint]:
        """Get domain-specific constraints (fallback only).

        In the new LLM architecture, constraints come from generate_specialist_output_llm().
        This method is only used as fallback when LLM fails.
        """
        return _get_minimal_safety_constraints(self.topic)

    def _calculate_activity_days(self, state: GraphState) -> int:
        """
        Calculate how many days are available for activities.

        For a trip:
        - Day 1 = Arrival (no activities)
        - Day N = Departure (no activities)
        - Diving: Day N-1 = No-fly buffer (no diving)
        - Hiking at high altitude: Day 3 = Acclimatization (no strenuous activity)

        Returns the number of days available for specialist activities.
        For very short trips (1-2 days), returns 0 (no activity days).
        Result is cached on the instance for the duration of this specialist run.
        """
        if self._cached_activity_days is not None:
            return self._cached_activity_days

        plan = state.trip_plan

        from app.debug_utils import _debug_info

        _debug_info("SPECIALIST", "_calculate_activity_days called")
        _debug_info("SPECIALIST", f"  topic={self.topic}")
        _debug_info("SPECIALIST", f"  start_date={plan.start_date}")
        _debug_info("SPECIALIST", f"  end_date={plan.end_date}")

        if not plan.start_date or not plan.end_date:
            _debug_info("SPECIALIST", "  -> No dates, returning 3 (default)")
            self._cached_activity_days = 3
            return 3

        from datetime import datetime

        try:
            start = datetime.strptime(plan.start_date, "%Y-%m-%d")
            end = datetime.strptime(plan.end_date, "%Y-%m-%d")
            total_days = (end - start).days + 1
            _debug_info("SPECIALIST", f"  total_days={total_days}")
        except ValueError as e:
            _debug_info("SPECIALIST", f"  -> Date parse error: {e}, returning 3")
            self._cached_activity_days = 3
            return 3

        # Subtract arrival (day 1) and departure (last day)
        available = total_days - 2
        _debug_info("SPECIALIST", f"  after arrival/departure: available={available}")

        # Specialist-specific buffers (registry-driven)
        config = get_specialist_config(self.topic)
        if config and config.has_nofly_buffer:
            available -= 1
            _debug_info("SPECIALIST", f"  after {self.topic} no-fly buffer: available={available}")
        elif config and config.has_altitude_buffer:
            available -= 1  # Conservative — LLM handles content appropriately
            message = f"  after {self.topic} altitude buffer: available={available}"
            _debug_info("SPECIALIST", message)

        result = max(0, available)
        _debug_info("SPECIALIST", f"  -> FINAL: max_activities={result}")
        self._cached_activity_days = result
        return result

    def get_content_for_destination(
        self, destination: str, state: Optional[GraphState] = None
    ) -> List[ItineraryBlock]:
        """
        Get suggested activities for a destination.

        This is the S1/S2 content generation.
        Respects trip duration - only generates activities that fit.

        Priority:
        1. Curated content from demo_curation.py (has images for hero destinations)
        2. Hardcoded knowledge (fallback for non-hero destinations)
        """
        from app.debug_utils import _debug_info, _debug_log

        # Guard: return empty if no destination (prevents false matches)
        if not destination:
            _debug_log("[SPECIALIST] get_content_for_destination: No destination, returning empty")
            return []

        # Normalize destination name for lookup
        dest_lower = destination.lower().strip()

        # Extra safety: return empty if destination is effectively empty
        if not dest_lower:
            _debug_log(
                "[SPECIALIST] get_content_for_destination: Empty dest_lower, returning empty"
            )
            return []

        # Calculate available activity days from trip dates
        max_activities = self._calculate_activity_days(state) if state else 3
        _debug_info("SPECIALIST", f"get_content_for_destination: max_activities={max_activities}")

        # For very short trips (no activity days), return empty
        if max_activities <= 0:
            message = "get_content_for_destination: TRIP TOO SHORT - returning empty"
            _debug_info("SPECIALIST", message)
            return []

        # Check for curated content (includes images) - used for demo destinations
        # NOTE: In the new LLM architecture, activities primarily come from LLM.
        # This method is called as fallback only when LLM fails.
        _debug_log(
            f"[SPECIALIST] get_content_for_destination: "
            f"Looking up curated content for '{dest_lower}'"
        )
        curated_blocks = self._get_curated_content(dest_lower, max_activities)
        if curated_blocks:
            _debug_info(
                "SPECIALIST",
                f"Returning {len(curated_blocks)} curated blocks (max was {max_activities})",
            )
            return curated_blocks

        # No curated content found - return empty (LLM is primary source now)
        _debug_log(
            f"[SPECIALIST] get_content_for_destination: "
            f"No curated content for '{dest_lower}', returning empty (LLM is primary source)"
        )
        return []

    def _get_curated_content(
        self, destination: str, max_activities: int = 3
    ) -> List[ItineraryBlock]:
        """
        Get curated content from demo_curation.py if available.

        Returns ItineraryBlocks with images for hero destinations.
        Limited to max_activities based on trip duration.
        """
        from app.debug_utils import _debug_log

        try:
            from app.data.demo_curation import DEMO_MANIFEST, is_hero_destination

            _debug_log(
                f"[SPECIALIST] _get_curated_content: "
                f"destination='{destination}', topic='{self.topic}', max={max_activities}"
            )

            is_hero = is_hero_destination(destination)
            _debug_log(f"[SPECIALIST] is_hero_destination('{destination}') = {is_hero}")

            if not is_hero:
                _debug_log("[SPECIALIST] NOT a hero destination, returning empty")
                return []

            _debug_log("[SPECIALIST] IS a hero destination, fetching curated content")
            manifest = DEMO_MANIFEST.get(destination.lower().strip(), {})
            specialist_content = manifest.get("specialist_content", {})
            _debug_log(f"[SPECIALIST] specialist_content keys: {list(specialist_content.keys())}")

            # Get activities for this specialist type
            activities = specialist_content.get(self.topic, [])
            _debug_log(f"[SPECIALIST] activities for topic '{self.topic}': {len(activities)}")

            if not activities:
                _debug_log("[SPECIALIST] No activities found, returning empty")
                return []

            blocks = []
            # Limit to max_activities based on trip duration
            for i, activity in enumerate(activities[:max_activities]):
                _debug_log(
                    f"[SPECIALIST] Creating block: {activity.get('title')}, "
                    f"image={bool(activity.get('image'))}, coords={activity.get('coordinates')}"
                )
                # Default skill_level by specialist type if not in curated data
                default_skill = {
                    "diving": "intermediate",
                    "hiking": "intermediate",
                    "skiing": "advanced",
                    "cycling": "intermediate",
                    "surfing": "intermediate",
                }.get(self.topic, "intermediate")

                blocks.append(
                    ItineraryBlock(
                        day=i + 2,  # Start from day 2 (day 1 is arrival)
                        title=activity.get("title", ""),
                        description=activity.get("description", ""),
                        type=activity.get("type", "activity"),
                        source_specialist=self.topic,
                        skill_level=activity.get("skill_level", default_skill),
                        logic_hook=activity.get("logic_hook"),
                        image_url=activity.get("image"),  # Curated image URL
                        coordinates=activity.get("coordinates"),  # [lng, lat] for Mapbox
                    )
                )

            _debug_log(
                f"[SPECIALIST] Returning {len(blocks)} curated blocks (max was {max_activities})"
            )
            return blocks

        except ImportError:
            return []

    def critique_plan(self, state: GraphState) -> Optional[str]:
        """
        Review current plan from domain expertise perspective.

        Returns critique if issues found, None otherwise.
        """
        plan = state.trip_plan

        # Check for constraint violations
        if self.topic == "diving":
            # Check if there's a flight on the last day
            if plan.segments:
                for segment in plan.segments:
                    if segment.type == "flight":
                        # In real implementation, check dates
                        pass

        return None

    def generate_enhancements(self, _state: GraphState) -> List[str]:
        """
        Suggest enhancements to the plan. Data-driven from registry.
        """
        config = get_specialist_config(self.topic)
        if config and config.enhancements:
            return list(config.enhancements)
        return []

    def generate_bookends(self, state: GraphState) -> List[ItineraryBlock]:
        """
        Generate arrival/departure bookend blocks.

        Day 1: Arrival + Check-in
        Last Day: Check-out + Departure
        """
        plan = state.trip_plan
        blocks = []

        # Calculate trip duration
        if plan.start_date and plan.end_date:
            from datetime import datetime

            try:
                start = datetime.strptime(plan.start_date, "%Y-%m-%d")
                end = datetime.strptime(plan.end_date, "%Y-%m-%d")
                duration = (end - start).days + 1
            except ValueError:
                duration = 5  # Default
        else:
            duration = 5  # Default

        destination = plan.destination or "your destination"

        # Day 1: Arrival
        blocks.append(
            ItineraryBlock(
                day=1,
                title=f"Arrival in {destination}",
                description="Airport transfer and hotel check-in. Rest and acclimatize.",
                type="buffer",
                is_buffer=True,
                buffer_type="arrival",
                buffer_reason="Travel day - airport transfer and check-in",
                source_specialist=self.topic,
            )
        )

        # Last day: Departure
        blocks.append(
            ItineraryBlock(
                day=duration,
                title=f"Departure from {destination}",
                description="Hotel check-out and transfer to airport.",
                type="buffer",
                is_buffer=True,
                buffer_type="departure",
                buffer_reason="Travel day - check-out and departure",
                source_specialist=self.topic,
            )
        )

        return blocks

    def generate_safety_buffers(self, state: GraphState) -> List[ItineraryBlock]:
        """
        Generate safety buffer blocks based on domain constraints.

        - Diving: No-fly interval (24h before departure flight)
        - Hiking: Acclimatization days at high altitude
        """
        plan = state.trip_plan
        blocks = []

        # Calculate trip duration
        if plan.start_date and plan.end_date:
            from datetime import datetime

            try:
                start = datetime.strptime(plan.start_date, "%Y-%m-%d")
                end = datetime.strptime(plan.end_date, "%Y-%m-%d")
                duration = (end - start).days + 1
            except ValueError:
                duration = 5
        else:
            duration = 5

        # Registry-driven safety buffers
        config = get_specialist_config(self.topic)
        if not config:
            pass
        elif config.has_nofly_buffer and duration >= 3:
            # No-fly buffer shown as INLINE CONSTRAINT on last dive activity
            # (see itinerary_builder._apply_constraints_to_blocks)
            pass
        elif config.has_altitude_buffer and duration >= 4:
            blocks.append(
                ItineraryBlock(
                    day=3,
                    title="Acclimatization Day",
                    description=(
                        "Rest day to adjust to altitude. Light walks only, stay hydrated."
                    ),
                    type="buffer",
                    is_buffer=True,
                    buffer_type="acclimatization",
                    buffer_reason=(
                        "Altitude sickness prevention: max 500m elevation gain per day above 3000m"
                    ),
                    source_specialist=self.topic,
                    safety_notes=(
                        "Ascending too fast increases risk of AMS (Acute Mountain Sickness)"
                    ),
                )
            )

        return blocks

    async def generate_output(self, state: GraphState) -> SpecialistOutput:
        """
        Generate the complete specialist output.

        NEW ARCHITECTURE (Zero-Template LLM):
        1. Check for cached parallel LLM results (from generate_all_specialists_parallel)
        2. If not cached, try LLM generation
        3. If LLM fails, fall back to hardcoded knowledge

        Returns BOTH constraints AND content.
        """
        from app.debug_utils import _debug_log

        destination = state.trip_plan.destination or ""
        started_at = time.monotonic()
        latency_source = "hardcoded_fallback"
        latency_reason = "none"

        def _record_latency(source: str, reason: str = "none") -> None:
            elapsed_ms = int((time.monotonic() - started_at) * 1000)
            _record_specialist_latency_metric(
                state=state,
                topic=self.topic,
                source=source,
                elapsed_ms=elapsed_ms,
                reason=reason,
            )

        # DEBUG: Log input state
        _debug_log(
            f"[SPECIALIST] generate_output called: topic={self.topic}, destination='{destination}'"
        )
        _debug_log(
            f"[SPECIALIST] trip_plan: start_date={state.trip_plan.start_date}, "
            f"end_date={state.trip_plan.end_date}"
        )

        # =====================================================================
        # STEP 0a: Early feasibility check - trip too short for this activity?
        # =====================================================================
        activity_days = self._calculate_activity_days(state)
        if activity_days <= 0:
            # Trip is too short for this specialist's activities
            config = get_specialist_config(self.topic)
            min_days_needed = config.min_days_needed if config else 3

            reason = (
                f"{self.topic.title()} requires at least {min_days_needed} days "
                f"(your trip is too short). "
            )
            if config and config.has_nofly_buffer:
                reason += "The 24h no-fly safety buffer leaves no time for activity."

            _debug_log(f"[SPECIALIST] INFEASIBLE: Trip too short for {self.topic}")
            _record_latency("rule_short_trip", "insufficient_days")
            return SpecialistOutput(
                feasibility_status="infeasible",
                feasibility_reason=reason,
                alternative_suggestion=(
                    f"Consider extending your trip to {min_days_needed}+ days, "
                    f"or explore other activities."
                ),
                constraints=[],
                content_blocks=[],
                critique=None,
                enhancements=[],
            )

        # =====================================================================
        # STEP 0b: Check for cached parallel LLM results (PERFORMANCE OPTIMIZATION)
        # =====================================================================
        parallel_results = state.metadata.get("parallel_llm_results", {})
        cached_result = parallel_results.get(self.topic)
        llm_output: Optional[LLMSpecialistOutput] = None

        if cached_result is not None:
            # Deserialize from dict (cached results are stored via model_dump())
            try:
                llm_output = LLMSpecialistOutput.model_validate(cached_result)
                latency_source = "parallel_cache"
                _debug_log(
                    f"[SPECIALIST] Using CACHED parallel result for {self.topic}: "
                    f"status={llm_output.feasibility_status}, "
                    f"activities={len(llm_output.activities)}"
                )
            except Exception as e:
                _debug_log(f"[SPECIALIST] Failed to deserialize cached result: {e}")
                latency_reason = "parallel_cache_deserialize_error"
                llm_output = None
        else:
            # =====================================================================
            # STEP 1: Try LLM-based generation (fallback if not parallel)
            # =====================================================================
            use_llm = load_prompt(self.topic) is not None

            if use_llm and destination:
                _debug_log(f"[SPECIALIST] Trying LLM generation for {self.topic} in {destination}")
                try:
                    # Native async - no event loop blocking
                    _skill = (
                        state.metadata.get("trip_inputs", {})
                        .get("activity_settings", {})
                        .get("skill_level")
                    )
                    llm_output = await generate_specialist_output_llm(
                        self.topic,
                        destination,
                        state.trip_plan,
                        skill_level=_skill,
                    )
                    latency_source = "llm_path"
                except Exception as e:
                    _debug_log(f"[SPECIALIST] LLM generation failed: {e}, using hardcoded fallback")
                    latency_reason = f"llm_error:{type(e).__name__}"
            else:
                latency_reason = "llm_unavailable_or_missing_destination"

        # =====================================================================
        # STEP 1.5: Process LLM output (cached or fresh)
        # =====================================================================
        if llm_output:
            _debug_log(
                f"[SPECIALIST] LLM SUCCESS: status={llm_output.feasibility_status}, "
                f"activities={len(llm_output.activities)}, "
                f"constraints={len(llm_output.constraints)}"
            )

            # Handle infeasible from LLM
            if llm_output.feasibility_status == "infeasible":
                _record_latency(latency_source, "llm_infeasible")
                return SpecialistOutput(
                    feasibility_status="infeasible",
                    feasibility_reason=llm_output.feasibility_reason,
                    alternative_suggestion=llm_output.feasibility_reason,
                    constraints=[],
                    content_blocks=[],
                    critique=None,
                    enhancements=[],
                )

            # Fire-and-forget Unsplash prefetch — don't block specialist pipeline.
            # Images are cosmetic; placeholder gradients render fine without them.
            try:
                from app.services.unsplash import prefetch_destination_images

                asyncio.create_task(
                    prefetch_destination_images(destination, activities=[self.topic])
                )
                _debug_log(
                    f"[SPECIALIST] Unsplash prefetch fired (non-blocking) "
                    f"for {destination}/{self.topic}"
                )
            except Exception as e:
                _debug_log(f"[SPECIALIST] Unsplash prefetch error (non-fatal): {e}")

            # Convert LLM output to SpecialistOutput format
            converted = convert_llm_output_to_specialist_output(llm_output, self.topic, destination)

            # Add bookends (arrival/departure) - always deterministic
            bookends = self.generate_bookends(state)
            all_blocks = bookends + converted.content_blocks
            all_blocks.sort(key=lambda b: b.day)

            # Add safety buffers
            safety_buffers = self.generate_safety_buffers(state)
            all_blocks.extend(safety_buffers)
            all_blocks.sort(key=lambda b: b.day)

            # Migrate any legacy constraints
            constraints = _migrate_legacy_constraints(converted.constraints)

            # Replace LLM-generated constraints with hardcoded ones (proper IDs/labels)
            # LLM constraints have garbage numeric IDs ("1", "2", "3") - hardcoded are cleaner
            safety_constraints = _get_minimal_safety_constraints(self.topic, destination)
            if safety_constraints:
                constraints = safety_constraints
                _debug_log(
                    f"[SPECIALIST] Replaced LLM constraints with {len(constraints)} hardcoded"
                )

            _record_latency(latency_source)
            return SpecialistOutput(
                feasibility_status=llm_output.feasibility_status,
                feasibility_reason=llm_output.feasibility_reason,
                constraints=constraints,
                content_blocks=all_blocks,
                critique=None,
                enhancements=self.generate_enhancements(state),
            )

        # =====================================================================
        # STEP 2: FALLBACK - Use hardcoded knowledge (legacy path)
        # =====================================================================
        _debug_log(f"[SPECIALIST] Using hardcoded fallback for {self.topic}")

        # Check feasibility using hardcoded data
        status, reason, alternative = await check_feasibility(self.topic, destination)
        _debug_log(
            f"[SPECIALIST] feasibility: status={status}, reason={reason[:50] if reason else None}"
        )

        if status == "infeasible":
            _record_latency("hardcoded_fallback", latency_reason)
            return SpecialistOutput(
                feasibility_status="infeasible",
                feasibility_reason=reason,
                alternative_suggestion=alternative,
                constraints=[],
                content_blocks=[],
                critique=None,
                enhancements=[],
            )

        # Collect all content blocks
        all_blocks: List[ItineraryBlock] = []

        # Bookends (arrival/departure)
        bookends = self.generate_bookends(state)
        all_blocks.extend(bookends)

        # Safety buffers
        safety_buffers = self.generate_safety_buffers(state)
        all_blocks.extend(safety_buffers)

        # Activity content from hardcoded knowledge
        activity_content = self.get_content_for_destination(destination, state)
        all_blocks.extend(activity_content)

        # Sort by day
        all_blocks.sort(key=lambda b: b.day)

        # Get hardcoded constraints and migrate them
        constraints = _migrate_legacy_constraints(self.get_constraints())

        # If caveat, inject as first constraint (warning)
        if status == "caveat" and reason:
            constraints.insert(
                0,
                SpecialistConstraint(
                    constraint_id="feasibility_caveat",
                    type="safety",
                    rule="feasibility_caveat",
                    applies_to="activities",
                    reason=reason,
                ),
            )

        _record_latency("hardcoded_fallback", latency_reason)
        return SpecialistOutput(
            feasibility_status=status,
            feasibility_reason=reason if status == "caveat" else None,
            alternative_suggestion=alternative,
            constraints=constraints,
            content_blocks=all_blocks,
            critique=self.critique_plan(state),
            enhancements=self.generate_enhancements(state),
        )


# =============================================================================
# Prompt Loading (for future LLM-based specialist)
# =============================================================================


# =============================================================================
# Curated Image Lookup
# =============================================================================


def _get_curated_image(topic: str, destination: str, title: str) -> Optional[str]:
    """
    Get image URL from curated content if available.

    Looks up the demo_curation.py DEMO_MANIFEST for matching activity images.
    Returns None if no match found (graceful fallback for non-demo destinations).
    """
    from app.data.demo_curation import DEMO_MANIFEST

    dest_key = destination.lower().strip() if destination else ""
    manifest = DEMO_MANIFEST.get(dest_key, {})
    specialist_content = manifest.get("specialist_content", {})

    # Check specialist-specific content first
    activities = specialist_content.get(topic, [])
    for activity in activities:
        # Fuzzy match on title (case-insensitive, contains)
        activity_title = activity.get("title", "").lower()
        search_title = title.lower()
        if (
            activity_title == search_title
            or search_title in activity_title
            or activity_title in search_title
        ):
            return activity.get("image")

    # Check general content as fallback
    general = specialist_content.get("general", [])
    for activity in general:
        activity_title = activity.get("title", "").lower()
        search_title = title.lower()
        if (
            activity_title == search_title
            or search_title in activity_title
            or activity_title in search_title
        ):
            return activity.get("image")

    return None


# =============================================================================
# Helper: Merge one specialist's output into state (for multi-specialist loop)
# =============================================================================


async def _merge_specialist_into_state(
    state: GraphState,
    topic: str,
    node_start_time: float,
    clog,  # CompactLogger
) -> None:
    """
    Process a single specialist topic and merge its output into state.

    Extracted from vertical_specialist() to support batched multi-specialist
    processing in a single graph entry. Returns None — mutates state in place.

    On infeasible: returns early (caller loop continues to next specialist).
    On cache hit (selective regen): returns early (topic already in state).
    """
    from app.debug_utils import (
        _debug_log,
        _debug_node_timer_end,
        log,
    )

    topic_started_at = time.monotonic()

    # ─── Selective regeneration: skip if cached section still valid ───────
    existing_sections = state.metadata.get("strategy_sections", [])
    cached_section = next((s for s in existing_sections if s.get("specialist_type") == topic), None)

    # Extract current day_preference for this topic
    _current_day_pref = (
        state.metadata.get("trip_inputs", {})
        .get("activity_settings", {})
        .get("day_preferences", {})
        .get(topic)
    )

    if cached_section:
        cached_destination = (cached_section.get("subtitle") or "").lower().strip()
        cached_dates = cached_section.get("_cache_dates")
        cached_day_pref = cached_section.get("_cache_day_pref")
        current_destination = (state.trip_plan.destination or "").lower().strip()
        current_dates = f"{state.trip_plan.start_date}:{state.trip_plan.end_date}"

        if (
            cached_destination
            and cached_destination == current_destination
            and cached_dates
            and cached_dates == current_dates
            and cached_day_pref == _current_day_pref
        ):
            _debug_log(
                f"🤿 SPECIALIST [{topic}] Cache HIT: Reusing cached output "
                f"(destination={current_destination}, dates={current_dates})"
            )
            state.metadata["last_executed_specialist"] = topic

            _debug_node_timer_end(
                "specialist",
                "🤿",
                topic=topic,
                cache_hit=True,
            )

            clog.event("cache_hit", f"Specialist ({topic})", dest=current_destination)
            duration_ms = int((time.time() - node_start_time) * 1000)
            clog.node_end("SPECIALIST", duration_ms, topic=topic, status="cache_hit")
            _record_specialist_latency_metric(
                state=state,
                topic=topic,
                source="section_cache",
                elapsed_ms=int((time.monotonic() - topic_started_at) * 1000),
                reason="cache_hit",
            )
            return  # skip this topic, loop continues to next

        # Infeasibility is destination-dependent, not date-dependent.
        # Skiing in Bali stays infeasible regardless of trip duration.
        if (
            cached_section.get("feasibility_status") == "infeasible"
            and cached_destination
            and cached_destination == current_destination
        ):
            _debug_log(
                f"🤿 SPECIALIST [{topic}] Still infeasible at {current_destination} "
                f"(destination-level cache, dates irrelevant)"
            )
            state.metadata["last_executed_specialist"] = topic
            state.metadata["specialist_infeasible"] = True
            state.metadata["specialist_infeasible_reason"] = cached_section.get(
                "feasibility_reason"
            )
            state.metadata["specialist_alternative"] = cached_section.get("alternative_suggestion")
            state.active_agent_id = topic
            state.ui_events.append("SPECIALIST_INFEASIBLE")

            duration_ms = int((time.time() - node_start_time) * 1000)
            clog.node_end("SPECIALIST", duration_ms, topic=topic, status="infeasible_cached")
            _record_specialist_latency_metric(
                state=state,
                topic=topic,
                source="section_cache_infeasible",
                elapsed_ms=int((time.monotonic() - topic_started_at) * 1000),
                reason="destination_infeasible_cache",
            )
            return

        _debug_log(
            f"🤿 SPECIALIST [{topic}] Strategy cache stale: context changed "
            f"(dest: {cached_destination}->{current_destination}, "
            f"dates: {cached_dates}->{current_dates}) "
            "(parallel LLM cache may still be reusable)"
        )

    # ─── Create specialist and generate output ────────────────────────────
    specialist = VerticalSpecialist(topic)
    output = await specialist.generate_output(state)

    # Store specialist output in metadata (always, for UI rendering)
    state.metadata["specialist_output"] = output.model_dump()

    # Handle INFEASIBLE case - activity not possible at destination
    if output.feasibility_status == "infeasible":
        log("SPECIALIST", f"⛔ {topic.title()} INFEASIBLE in {state.trip_plan.destination}")
        log("SPECIALIST", f"   Reason: {output.feasibility_reason}")
        if output.alternative_suggestion:
            log("SPECIALIST", f"   Alternative: {output.alternative_suggestion}")

        state.constraints_violated.append(
            output.feasibility_reason or f"{topic.title()} not available at this destination"
        )

        state.metadata["specialist_infeasible"] = True
        state.metadata["specialist_infeasible_reason"] = output.feasibility_reason
        state.metadata["specialist_alternative"] = output.alternative_suggestion

        state.active_agent_id = topic
        state.ui_events.append("SPECIALIST_INFEASIBLE")

        state.metadata["specialist_message"] = (
            f"{topic.title()} is not available in {state.trip_plan.destination}. "
            f"{output.alternative_suggestion or 'Consider a different destination.'}"
        )

        _debug_node_timer_end(
            "specialist",
            "🤿",
            topic=topic,
            feasibility_status="infeasible",
            reason=output.feasibility_reason,
        )

        duration_ms = int((time.time() - node_start_time) * 1000)
        clog.node_end("SPECIALIST", duration_ms, topic=topic, status="infeasible")

        state.metadata["last_executed_specialist"] = topic

        # Upsert an empty infeasible section so any stale cached section
        # (from a prior turn where this specialist was feasible) gets replaced.
        infeasible_section = build_specialist_section(
            topic=topic,
            destination=state.trip_plan.destination,
            start_date=state.trip_plan.start_date,
            end_date=state.trip_plan.end_date,
            feasibility_status="infeasible",
            feasibility_reason=output.feasibility_reason,
            alternative_suggestion=output.alternative_suggestion,
            constraints=[],
            content_added=[],
            enhancements=[],
            hero_image=None,
            day_pref=_current_day_pref,
        )
        upsert_section(state.metadata, infeasible_section, mode="appendable")
        mark_topic_executed(state.metadata, topic)

        return  # infeasible — loop continues to next specialist

    # Handle CAVEAT case - activity possible with limitations
    if output.feasibility_status == "caveat":
        log("SPECIALIST", f"⚠️ {topic.title()} CAVEAT: {output.feasibility_reason}")
        state.metadata["specialist_caveat"] = True
        state.metadata["specialist_caveat_reason"] = output.feasibility_reason

    # FEASIBLE or CAVEAT: Inject constraints into trip plan
    for constraint in output.constraints:
        if constraint not in state.trip_plan.constraints:
            state.trip_plan.constraints.append(constraint)

    # Add content blocks to trip plan
    for block in output.content_blocks:
        if block not in state.trip_plan.itinerary_blocks:
            state.trip_plan.itinerary_blocks.append(block)

    # Persist specialist constraints to metadata for cross-turn survival
    if output.constraints:
        specialist_store = state.metadata.setdefault("specialist_constraints", {})
        specialist_store[topic] = [c.model_dump() for c in output.constraints]
        log("SPECIALIST", f"Persisted {len(output.constraints)} constraints to metadata['{topic}']")

    # Log constraints and content
    if output.constraints:
        constraint_rules = ", ".join([c.rule for c in output.constraints])
        log("SPECIALIST", "Constraints injected", data=constraint_rules)
    if output.content_blocks:
        log("SPECIALIST", f"Content blocks: {len(output.content_blocks)}")
        for block in output.content_blocks[:3]:
            log("SPECIALIST", f"  Day {block.day}: {block.title}", sleep=0.1)

    # Update UI state
    state.active_agent_id = topic
    state.ui_events.append("SPECIALIST_DONE")

    # Build strategy_section for UI display (with images from curated content)
    content_added = []
    for block in output.content_blocks:
        if block.is_buffer:
            continue
        image_url = block.image_url or _get_curated_image(
            topic, state.trip_plan.destination, block.title
        )
        skill_to_intensity = {
            "beginner": "light",
            "easy": "light",
            "intermediate": "moderate",
            "moderate": "moderate",
            "advanced": "challenging",
            "hard": "challenging",
            "challenging": "challenging",
        }
        default_intensity = {
            "diving": "moderate",
            "hiking": "moderate",
            "skiing": "challenging",
            "cycling": "moderate",
            "surfing": "moderate",
        }
        skill_key = block.skill_level.lower() if block.skill_level else None
        intensity = (
            skill_to_intensity.get(skill_key)
            if skill_key
            else default_intensity.get(topic, "moderate")
        )

        content_item = {
            "title": block.title,
            "description": block.description,
            "logic_hook": block.logic_hook,
            "type": block.type,
            "day": block.day,
            "image_url": image_url,
            "coordinates": block.coordinates,
            "intensity": intensity,
            "duration_hours": block.duration_hours,
        }
        content_added.append(content_item)

    # TRIM: Limit activities to what fits in the trip duration
    max_activities = specialist._calculate_activity_days(state)
    if max_activities > 0 and len(content_added) > max_activities:
        original_count = len(content_added)
        content_added = content_added[:max_activities]
        log("SPECIALIST", f"Trimmed activities: {original_count} → {max_activities}")

    # Determine hero_image
    hero_image = None
    if content_added:
        hero_image = content_added[0].get("image_url")
    if not hero_image:
        hero_image = get_activity_image(topic, state.trip_plan.destination or "", topic)

    section = build_specialist_section(
        topic=topic,
        destination=state.trip_plan.destination,
        start_date=state.trip_plan.start_date,
        end_date=state.trip_plan.end_date,
        feasibility_status=output.feasibility_status,
        feasibility_reason=output.feasibility_reason,
        alternative_suggestion=output.alternative_suggestion,
        constraints=[
            {
                "rule": c.rule,
                "reason": c.reason,
                "type": c.type,
                "severity": c.severity.value if hasattr(c.severity, "value") else str(c.severity),
            }
            for c in output.constraints
        ],
        content_added=content_added,
        enhancements=output.enhancements,
        hero_image=hero_image,
        day_pref=_current_day_pref,
    )

    upsert_section(state.metadata, section, mode="appendable")
    mark_topic_executed(state.metadata, topic)

    _debug_log(f"Strategy section created for {topic} with {len(content_added)} recommendations")
    reason_preview = output.feasibility_reason[:50] if output.feasibility_reason else None
    _debug_log(
        f"  feasibility_status={output.feasibility_status}, feasibility_reason={reason_preview}"
    )
    _debug_log(
        f"  constraints_count={len(output.constraints)}, "
        f"content_blocks_count={len(output.content_blocks)}"
    )
    _debug_log(f"  content_added titles: {[c.get('title') for c in content_added]}")
    _debug_log(f"  content_added has images: {[bool(c.get('image_url')) for c in content_added]}")

    # Generate specialist message for UI
    if output.content_blocks:
        block_titles = [b.title for b in output.content_blocks[:3]]
        caveat_note = (
            f" Note: {output.feasibility_reason}" if output.feasibility_status == "caveat" else ""
        )
        state.metadata["specialist_message"] = (
            f"I've added some {topic} experiences: {', '.join(block_titles)}. "
            f"I've also noted {len(output.constraints)} safety considerations.{caveat_note}"
        )

    _debug_node_timer_end(
        "specialist",
        "🤿",
        topic=topic,
        constraints_added=len(output.constraints),
        content_blocks_added=len(output.content_blocks),
        critique=output.critique[:50] if output.critique else None,
    )

    # Compact logging: success
    duration_ms = int((time.time() - node_start_time) * 1000)
    clog.node_end(
        "SPECIALIST",
        duration_ms,
        topic=topic,
        status=output.feasibility_status,
        constraints=len(output.constraints),
        activities=len(output.content_blocks),
    )

    # Track for downstream nodes (synthesizer, _v2_result_to_v1_format)
    state.metadata["last_executed_specialist"] = topic


# =============================================================================
# Node Function (for graph registration)
# =============================================================================


async def vertical_specialist(state: GraphState) -> GraphState:
    """
    VerticalSpecialist node function for LangGraph.

    The "Diving Agent" / "Hiking Agent" that injects domain expertise.

    CRITICAL: Multi-specialist support requires state mutations to happen HERE,
    not in routing functions (LangGraph doesn't persist routing function mutations).

    Flow:
    1. First run: Router sets active_specialist, we use it and clear it at end
    2. Routing sees pending_specialists not empty → routes back here
    3. Subsequent runs: active_specialist is None, we pop from pending_specialists
    """
    import time

    from app.debug_utils import (
        CompactLogger,
        _debug_log,
        _debug_node_start,
        _debug_node_timer_start,
        log,
    )

    # Start timing this node
    node_start_time = time.time()

    # Initialize compact logger with request metrics
    metrics = state.metadata.get("_metrics")
    clog = CompactLogger("specialist", metrics=metrics)

    # =========================================================================
    # FIRST THING: Invalidate stale cache if destination OR month changed
    # Must happen before ANY other logic for multi-specialist loops
    # =========================================================================
    cached_key = state.metadata.get("_last_specialist_key", "")
    current_dest = (state.trip_plan.destination or "").lower().strip()
    # Use month + duration bucket instead of exact dates — date extensions within
    # the same bucket don't change specialist LLM output (activity recommendations
    # depend on destination/month/duration-class, not exact start/end dates).
    # Matches the persistent specialist_cache strategy.
    start_date = state.trip_plan.start_date or ""
    end_date = state.trip_plan.end_date or ""
    _month = start_date[:7] if len(start_date) >= 7 else "no-month"
    try:
        from datetime import datetime as _dt

        _s = _dt.strptime(start_date[:10], "%Y-%m-%d")
        _e = _dt.strptime(end_date[:10], "%Y-%m-%d")
        _days = (_e - _s).days + 1
        _bucket = (
            "weekend"
            if _days <= 3
            else "short"
            if _days <= 5
            else "week"
            if _days <= 8
            else "extended"
            if _days <= 11
            else "twoweek"
            if _days <= 15
            else "long"
        )
    except (ValueError, TypeError):
        _bucket = "unknown"
    # Include day_preferences so stepper changes bust the parallel_llm_results cache
    # Only include Tier 1 specialist prefs — Tier 2 category changes (nightlife, yoga)
    # don't affect specialist outputs and shouldn't invalidate the cache.
    _all_day_prefs = (
        state.metadata.get("trip_inputs", {})
        .get("activity_settings", {})
        .get("day_preferences", {})
    )
    _tier1_prefs = (
        {k: v for k, v in _all_day_prefs.items() if k in TIER1_SPECIALIST_NAMES}
        if _all_day_prefs
        else {}
    )
    _dp_suffix = json.dumps(_tier1_prefs, sort_keys=True) if _tier1_prefs else ""
    current_key = f"{current_dest}:{_month}:{_bucket}:{_dp_suffix}"

    if cached_key and cached_key != current_key:
        _debug_log(
            f"[SPECIALIST] Context changed ({cached_key} → {current_key}), "
            "invalidating parallel_llm_results"
        )
        state.metadata.pop("parallel_llm_results", None)
    else:
        _debug_log(f"[SPECIALIST] Context unchanged ({current_key}), preserving cache")

    # Store current key for next comparison
    state.metadata["_last_specialist_key"] = current_key

    # Start timing this node execution
    _debug_node_timer_start("specialist")

    # MULTI-SPECIALIST SUPPORT: Pop from pending if active_specialist is not set
    # On first run, router sets active_specialist. On loop iterations, we pop from pending.
    if not state.active_specialist and state.pending_specialists:
        next_specialist = state.pending_specialists[0]
        state.pending_specialists = state.pending_specialists[1:]
        state.active_specialist = next_specialist
        state.active_agent_id = next_specialist
        state.ui_events.append("SPECIALIST_ACTIVE")
        log("SPECIALIST", f"Multi-specialist loop: popped '{next_specialist}' from queue")

    topic = state.active_specialist

    if not topic:
        # No specialist needed - pass through
        _debug_log("🤿 SPECIALIST skipped (no active specialist)")
        # Compact logging: skipped
        duration_ms = int((time.time() - node_start_time) * 1000)
        clog.node_end("SPECIALIST", duration_ms, status="skipped", reason="no_active_specialist")
        return state

    # Compact logging: node start
    clog.node_start("SPECIALIST", topic=topic, dest=state.trip_plan.destination)

    # NOTE: Selective regeneration check moved into _merge_specialist_into_state()
    # to support batched multi-specialist processing without orphaning specialists.

    _debug_node_start(
        "specialist",
        "🤿",
        topic=topic,
        destination=state.trip_plan.destination,
    )

    # DEBUG: Log full trip plan state
    _debug_log(
        f"[SPECIALIST] FULL STATE: start_date={state.trip_plan.start_date}, "
        f"end_date={state.trip_plan.end_date}"
    )
    _debug_log(
        f"[SPECIALIST] FULL STATE: adults={state.trip_plan.adults}, "
        f"children={state.trip_plan.children}"
    )
    tiles_count = sum(len(v) for v in state.tiles.values()) if state.tiles else 0
    _debug_log(f"[SPECIALIST] FULL STATE: tiles_count={tiles_count}")
    existing_sections = [
        s.get("specialist_type") for s in state.metadata.get("strategy_sections", [])
    ]
    _debug_log(f"[SPECIALIST] FULL STATE: existing_strategy_sections={existing_sections}")

    log("SPECIALIST", f"{topic.title()} Specialist activated")
    log("SPECIALIST", f"Destination from trip_plan: '{state.trip_plan.destination}'")
    dest_from_inputs = state.trip_plan.destination
    log(
        "SPECIALIST",
        f"Destination from trip_plan (canonical): '{dest_from_inputs}'",
    )

    # Verify destination is set - critical for correct content
    if not state.trip_plan.destination:
        log("SPECIALIST", "⚠️ WARNING: No destination set in trip_plan!")

    # =========================================================================
    # PARALLEL LLM OPTIMIZATION: Trigger parallel generation on first specialist
    # =========================================================================
    # If this is the first specialist call AND there are multiple specialists,
    # generate all LLM outputs in parallel and cache them for subsequent calls.
    # This reduces wall time from 8-12s (sequential) to 4-6s (parallel).
    #
    # NEW: Pass database session for L1+L2 persistent caching (7-day TTL).
    #
    # Collect all specialists that need processing
    all_specialists = [topic] + list(state.pending_specialists)

    # Skip specialists already known to be infeasible at this destination.
    existing_sections = state.metadata.get("strategy_sections", [])
    dest_norm = (state.trip_plan.destination or "").lower().strip()
    dest_infeasible = {
        s.get("specialist_type")
        for s in existing_sections
        if s.get("feasibility_status") == "infeasible"
        and (s.get("subtitle") or "").lower().strip() == dest_norm
    }
    if dest_infeasible & set(all_specialists):
        skipped = dest_infeasible & set(all_specialists)
        all_specialists = [t for t in all_specialists if t not in dest_infeasible]
        _debug_log(f"[SPECIALIST] Filtered {skipped} from parallel batch (destination-infeasible)")

    # Determine which topics still need LLM generation
    existing_parallel = state.metadata.get("parallel_llm_results", {})
    topics_needing_gen = [t for t in all_specialists if t not in existing_parallel]

    if topics_needing_gen:
        from app.db import _get_async_session_factory

        async_session_factory = _get_async_session_factory()
        _skill = get_trip_settings(state).activity_settings.skill_level

        if len(topics_needing_gen) > 1:
            _debug_log(
                f"[SPECIALIST] PARALLEL TRIGGER: {len(topics_needing_gen)} specialists "
                f"({topics_needing_gen}), running in parallel"
            )

            async with async_session_factory() as db:
                parallel_results = await generate_all_specialists_parallel(
                    topics=topics_needing_gen,
                    destination=state.trip_plan.destination,
                    trip_plan=state.trip_plan,
                    db=db,
                    skill_level=_skill,
                    day_preferences=_all_day_prefs or None,
                )

            new_results = {k: v.model_dump() if v else None for k, v in parallel_results.items()}
            # Merge into existing results (preserves cached topics)
            existing_parallel.update(new_results)
            state.metadata["parallel_llm_results"] = existing_parallel

            _debug_log(
                f"[SPECIALIST] PARALLEL COMPLETE: {len(new_results)} new, "
                f"{len(existing_parallel)} total cached"
            )
        else:
            # Single specialist — cache lookup + LLM fallback
            single_topic = topics_needing_gen[0]
            _debug_log(f"[SPECIALIST] Single specialist '{single_topic}' - using cached LLM path")

            from app.services.specialist_cache import (
                get_cached_specialist_output,
            )

            try:
                async with async_session_factory() as db:
                    _debug_log(
                        f"[SPECIALIST_CACHE] Looking up cache for {single_topic} "
                        f"in {state.trip_plan.destination} "
                        f"dates={state.trip_plan.start_date}->{state.trip_plan.end_date}"
                    )
                    _topic_day_pref = _all_day_prefs.get(single_topic) if _all_day_prefs else None
                    cached_result = await get_cached_specialist_output(
                        db=db,
                        topic=single_topic,
                        destination=state.trip_plan.destination,
                        start_date=state.trip_plan.start_date,
                        end_date=state.trip_plan.end_date,
                        skill_level=_skill,
                        day_pref=_topic_day_pref,
                    )

                    if cached_result:
                        _debug_log(f"[SPECIALIST_CACHE] HIT for {single_topic} - skipping LLM")
                        existing_parallel[single_topic] = cached_result
                    else:
                        _debug_log(f"[SPECIALIST_CACHE] MISS for {single_topic} - calling LLM")
                        llm_result = await generate_specialist_output_llm(
                            topic=single_topic,
                            destination=state.trip_plan.destination,
                            trip_plan=state.trip_plan,
                            db=db,
                            skill_level=_skill,
                            target_activities=_topic_day_pref,
                        )

                        if llm_result:
                            _debug_log(
                                f"[SPECIALIST_CACHE] LLM success for {single_topic}: "
                                f"status={llm_result.feasibility_status}, "
                                f"activities={len(llm_result.activities)}"
                            )
                            existing_parallel[single_topic] = llm_result.model_dump()
                        else:
                            _debug_log(f"[SPECIALIST_CACHE] LLM returned None for {single_topic}")

                    state.metadata["parallel_llm_results"] = existing_parallel

            except Exception as e:
                _debug_log(f"[SPECIALIST_CACHE] Error: {e}")
                state.metadata["parallel_llm_results"] = existing_parallel
    else:
        _debug_log(f"[SPECIALIST] All {len(all_specialists)} topics already in parallel cache")

    # =========================================================================
    # MULTI-SPECIALIST BATCH: Process all specialists in a single graph entry
    # =========================================================================
    all_topics = [topic] + list(state.pending_specialists)
    state.pending_specialists = []  # Drain queue — we handle all of them here

    # ─── Filter out selectively-cached topics (no point prefetching images) ───
    existing_sections = state.metadata.get("strategy_sections", [])
    current_destination = state.trip_plan.destination
    current_dates = f"{state.trip_plan.start_date}:{state.trip_plan.end_date}"

    topics_to_prefetch = []
    for t in all_topics:
        cached = next((s for s in existing_sections if s.get("specialist_type") == t), None)
        if cached:
            cached_dest = cached.get("subtitle")
            cached_dt = cached.get("_cache_dates")
            if cached_dest == current_destination and cached_dt == current_dates:
                continue  # cached — skip prefetch
        topics_to_prefetch.append(t)

    # ─── Fire-and-forget Unsplash prefetch for non-cached topics ─────────
    # Don't block the specialist pipeline waiting for images.
    # Images arrive in background; placeholder gradients fill gaps.
    if len(topics_to_prefetch) > 1:
        import asyncio

        from app.services.unsplash import prefetch_destination_images

        for t in topics_to_prefetch:
            try:
                asyncio.create_task(
                    prefetch_destination_images(state.trip_plan.destination, activities=[t])
                )
            except Exception:
                pass  # non-fatal
        _debug_log(
            f"[SPECIALIST] Unsplash prefetch fired (non-blocking): "
            f"{len(topics_to_prefetch)} topics ({topics_to_prefetch})"
        )

    # ─── Sequential processing loop ──────────────────────────────────────
    for current_topic in all_topics:
        state.active_specialist = current_topic
        state.active_agent_id = current_topic
        state.ui_events.append("SPECIALIST_ACTIVE")
        log(
            "SPECIALIST",
            f"Processing {current_topic} ({all_topics.index(current_topic) + 1}/{len(all_topics)})",
        )

        await _merge_specialist_into_state(state, current_topic, node_start_time, clog)

    state.active_specialist = None  # Clear after all specialists processed
    return state
