"""
Known places database for confidence scoring and validation.

This module provides:
- Large sets of known cities, countries, regions for validation
- Ambiguous entity detection (Jordan = country or name?)
"""

from typing import Dict, FrozenSet, List, Optional

# =============================================================================
# KNOWN PLACES DATABASE
# =============================================================================

# Major world cities (500+)
KNOWN_CITIES: FrozenSet[str] = frozenset(
    {
        # North America
        "New York",
        "NYC",
        "Los Angeles",
        "LA",
        "Chicago",
        "Houston",
        "Phoenix",
        "Philadelphia",
        "San Antonio",
        "San Diego",
        "Dallas",
        "San Jose",
        "Austin",
        "Jacksonville",
        "Fort Worth",
        "Columbus",
        "Charlotte",
        "San Francisco",
        "SF",
        "Indianapolis",
        "Seattle",
        "Denver",
        "Washington",
        "Washington DC",
        "DC",
        "Boston",
        "El Paso",
        "Nashville",
        "Detroit",
        "Oklahoma City",
        "Portland",
        "Las Vegas",
        "Vegas",
        "Memphis",
        "Louisville",
        "Baltimore",
        "Milwaukee",
        "Albuquerque",
        "Tucson",
        "Fresno",
        "Sacramento",
        "Mesa",
        "Kansas City",
        "Atlanta",
        "Miami",
        "Oakland",
        "Minneapolis",
        "Tulsa",
        "Cleveland",
        "Wichita",
        "Arlington",
        "New Orleans",
        "Bakersfield",
        "Tampa",
        "Honolulu",
        "Aurora",
        "Anaheim",
        "Santa Ana",
        "St. Louis",
        "Riverside",
        "Corpus Christi",
        "Lexington",
        "Pittsburgh",
        "Anchorage",
        "Stockton",
        "Cincinnati",
        "St. Paul",
        "Toledo",
        "Greensboro",
        "Newark",
        "Plano",
        "Henderson",
        "Lincoln",
        "Buffalo",
        "Jersey City",
        "Chula Vista",
        "Fort Wayne",
        "Orlando",
        "Salt Lake City",
        "SLC",
        # Canada
        "Toronto",
        "Montreal",
        "Vancouver",
        "Calgary",
        "Edmonton",
        "Ottawa",
        "Winnipeg",
        "Quebec City",
        "Hamilton",
        "Victoria",
        # Mexico
        "Mexico City",
        "Guadalajara",
        "Monterrey",
        "Cancun",
        "Tijuana",
        "Puebla",
        "Playa del Carmen",
        "Cabo San Lucas",
        "Puerto Vallarta",
        "Oaxaca",
        # Central/South America
        "Sao Paulo",
        "São Paulo",
        "Rio de Janeiro",
        "Rio",
        "Buenos Aires",
        "Lima",
        "Bogota",
        "Bogotá",
        "Santiago",
        "Caracas",
        "Quito",
        "La Paz",
        "Montevideo",
        "Asuncion",
        "Asunción",
        "Medellin",
        "Medellín",
        "Cartagena",
        "Cusco",
        "Havana",
        "San Juan",
        "Panama City",
        "Guatemala City",
        "Managua",
        "Tegucigalpa",
        "San Salvador",
        # Europe - UK/Ireland
        "London",
        "Manchester",
        "Birmingham",
        "Liverpool",
        "Leeds",
        "Glasgow",
        "Edinburgh",
        "Bristol",
        "Cardiff",
        "Belfast",
        "Dublin",
        "Cork",
        "Galway",
        # Europe - France
        "Paris",
        "Marseille",
        "Lyon",
        "Toulouse",
        "Nice",
        "Nantes",
        "Strasbourg",
        "Montpellier",
        "Bordeaux",
        "Lille",
        "Rennes",
        "Cannes",
        "Monaco",
        # Europe - Germany
        "Berlin",
        "Hamburg",
        "Munich",
        "München",
        "Cologne",
        "Köln",
        "Frankfurt",
        "Stuttgart",
        "Dusseldorf",
        "Düsseldorf",
        "Leipzig",
        "Dortmund",
        "Essen",
        "Bremen",
        "Dresden",
        "Hanover",
        "Nuremberg",
        "Nürnberg",
        # Europe - Italy
        "Rome",
        "Roma",
        "Milan",
        "Milano",
        "Naples",
        "Napoli",
        "Turin",
        "Torino",
        "Palermo",
        "Genoa",
        "Genova",
        "Bologna",
        "Florence",
        "Firenze",
        "Venice",
        "Venezia",
        "Verona",
        "Catania",
        "Bari",
        "Messina",
        "Padua",
        "Trieste",
        # Europe - Spain
        "Madrid",
        "Barcelona",
        "Valencia",
        "Seville",
        "Sevilla",
        "Zaragoza",
        "Malaga",
        "Málaga",
        "Murcia",
        "Palma",
        "Las Palmas",
        "Bilbao",
        "Alicante",
        "Cordoba",
        "Córdoba",
        "Granada",
        "San Sebastian",
        # Europe - Portugal
        "Lisbon",
        "Porto",
        "Braga",
        "Coimbra",
        "Funchal",
        "Faro",
        # Europe - Netherlands
        "Amsterdam",
        "Rotterdam",
        "The Hague",
        "Utrecht",
        "Eindhoven",
        "Tilburg",
        # Europe - Belgium
        "Brussels",
        "Antwerp",
        "Ghent",
        "Bruges",
        "Liege",
        "Leuven",
        # Europe - Switzerland
        "Zurich",
        "Zürich",
        "Geneva",
        "Genève",
        "Basel",
        "Bern",
        "Lausanne",
        "Lucerne",
        "Luzern",
        "Interlaken",
        "Zermatt",
        "St. Moritz",
        # Europe - Austria
        "Vienna",
        "Wien",
        "Salzburg",
        "Innsbruck",
        "Graz",
        "Linz",
        # Europe - Scandinavia
        "Copenhagen",
        "København",
        "Stockholm",
        "Oslo",
        "Helsinki",
        "Gothenburg",
        "Malmö",
        "Bergen",
        "Reykjavik",
        "Reykjavík",
        # Europe - Eastern
        "Prague",
        "Praha",
        "Budapest",
        "Warsaw",
        "Warszawa",
        "Krakow",
        "Kraków",
        "Bucharest",
        "București",
        "Sofia",
        "Belgrade",
        "Beograd",
        "Zagreb",
        "Ljubljana",
        "Bratislava",
        "Tallinn",
        "Riga",
        "Vilnius",
        "Kyiv",
        "Kiev",
        "Lviv",
        "Odessa",
        "Minsk",
        "Chisinau",
        # Europe - Greece/Turkey
        "Athens",
        "Athina",
        "Thessaloniki",
        "Santorini",
        "Mykonos",
        "Rhodes",
        "Crete",
        "Heraklion",
        "Corfu",
        "Istanbul",
        "Ankara",
        "Izmir",
        "Antalya",
        "Bodrum",
        "Cappadocia",
        # Middle East
        "Dubai",
        "Abu Dhabi",
        "Doha",
        "Riyadh",
        "Jeddah",
        "Kuwait City",
        "Manama",
        "Muscat",
        "Amman",
        "Beirut",
        "Tel Aviv",
        "Jerusalem",
        "Haifa",
        "Petra",
        "Dead Sea",
        # Africa
        "Cairo",
        "Alexandria",
        "Marrakech",
        "Marrakesh",
        "Casablanca",
        "Fes",
        "Tangier",
        "Cape Town",
        "Johannesburg",
        "Durban",
        "Pretoria",
        "Nairobi",
        "Mombasa",
        "Dar es Salaam",
        "Zanzibar",
        "Addis Ababa",
        "Lagos",
        "Accra",
        "Dakar",
        "Tunis",
        "Algiers",
        "Mauritius",
        # Asia - East
        "Tokyo",
        "Osaka",
        "Kyoto",
        "Yokohama",
        "Nagoya",
        "Sapporo",
        "Fukuoka",
        "Kobe",
        "Hiroshima",
        "Nara",
        "Okinawa",
        "Beijing",
        "Shanghai",
        "Guangzhou",
        "Shenzhen",
        "Chengdu",
        "Hangzhou",
        "Xian",
        "Xi'an",
        "Nanjing",
        "Wuhan",
        "Chongqing",
        "Suzhou",
        "Guilin",
        "Hong Kong",
        "Macau",
        "Macao",
        "Seoul",
        "Busan",
        "Incheon",
        "Jeju",
        "Taipei",
        "Kaohsiung",
        "Taichung",
        # Asia - Southeast
        "Singapore",
        "Kuala Lumpur",
        "KL",
        "Penang",
        "Langkawi",
        "Johor Bahru",
        "Bangkok",
        "Phuket",
        "Chiang Mai",
        "Pattaya",
        "Krabi",
        "Koh Samui",
        "Ho Chi Minh City",
        "Saigon",
        "Hanoi",
        "Da Nang",
        "Hoi An",
        "Nha Trang",
        "Jakarta",
        "Bali",
        "Ubud",
        "Yogyakarta",
        "Surabaya",
        "Lombok",
        "Manila",
        "Cebu",
        "Boracay",
        "Palawan",
        "El Nido",
        "Phnom Penh",
        "Siem Reap",
        "Vientiane",
        "Luang Prabang",
        "Yangon",
        # Asia - South
        "Mumbai",
        "Bombay",
        "Delhi",
        "New Delhi",
        "Bangalore",
        "Bengaluru",
        "Chennai",
        "Madras",
        "Kolkata",
        "Calcutta",
        "Hyderabad",
        "Ahmedabad",
        "Pune",
        "Jaipur",
        "Udaipur",
        "Goa",
        "Agra",
        "Varanasi",
        "Kerala",
        "Kathmandu",
        "Pokhara",
        "Colombo",
        "Kandy",
        "Dhaka",
        "Karachi",
        "Lahore",
        "Islamabad",
        # Asia - Central
        "Tashkent",
        "Samarkand",
        "Bukhara",
        "Almaty",
        "Astana",
        "Bishkek",
        "Dushanbe",
        "Ashgabat",
        "Baku",
        "Tbilisi",
        "Yerevan",
        # Oceania
        "Sydney",
        "Melbourne",
        "Brisbane",
        "Perth",
        "Adelaide",
        "Canberra",
        "Gold Coast",
        "Cairns",
        "Darwin",
        "Hobart",
        "Auckland",
        "Wellington",
        "Christchurch",
        "Queenstown",
        "Rotorua",
        "Fiji",
        "Suva",
        "Tahiti",
        "Bora Bora",
        "Moorea",
    }
)

# Countries and territories (200+)
KNOWN_COUNTRIES: FrozenSet[str] = frozenset(
    {
        # North America
        "USA",
        "United States",
        "United States of America",
        "America",
        "US",
        "Canada",
        "Mexico",
        # Central America & Caribbean
        "Guatemala",
        "Belize",
        "Honduras",
        "El Salvador",
        "Nicaragua",
        "Costa Rica",
        "Panama",
        "Cuba",
        "Jamaica",
        "Haiti",
        "Dominican Republic",
        "Puerto Rico",
        "Bahamas",
        "Barbados",
        "Trinidad and Tobago",
        "Aruba",
        "Curacao",
        "Curaçao",
        "St. Lucia",
        "Saint Lucia",
        "Antigua",
        "Antigua and Barbuda",
        "St. Kitts",
        "Grenada",
        "St. Vincent",
        "Virgin Islands",
        "BVI",
        "USVI",
        "Cayman Islands",
        "Turks and Caicos",
        # South America
        "Brazil",
        "Argentina",
        "Colombia",
        "Peru",
        "Venezuela",
        "Chile",
        "Ecuador",
        "Bolivia",
        "Paraguay",
        "Uruguay",
        "Guyana",
        "Suriname",
        "French Guiana",
        # Europe - Western
        "UK",
        "United Kingdom",
        "Great Britain",
        "Britain",
        "England",
        "Scotland",
        "Wales",
        "Northern Ireland",
        "Ireland",
        "France",
        "Germany",
        "Italy",
        "Spain",
        "Portugal",
        "Netherlands",
        "Holland",
        "Belgium",
        "Luxembourg",
        "Switzerland",
        "Austria",
        "Liechtenstein",
        "Monaco",
        "Andorra",
        "San Marino",
        "Vatican",
        "Vatican City",
        # Europe - Northern
        "Denmark",
        "Norway",
        "Sweden",
        "Finland",
        "Iceland",
        "Greenland",
        "Faroe Islands",
        # Europe - Eastern
        "Poland",
        "Czech Republic",
        "Czechia",
        "Slovakia",
        "Hungary",
        "Romania",
        "Bulgaria",
        "Serbia",
        "Croatia",
        "Slovenia",
        "Bosnia",
        "Bosnia and Herzegovina",
        "Montenegro",
        "North Macedonia",
        "Macedonia",
        "Albania",
        "Kosovo",
        "Moldova",
        "Ukraine",
        "Belarus",
        "Russia",
        "Estonia",
        "Latvia",
        "Lithuania",
        # Europe - Southern
        "Greece",
        "Turkey",
        "Cyprus",
        "Malta",
        # Middle East
        "Israel",
        "Palestine",
        "Jordan",
        "Lebanon",
        "Syria",
        "Iraq",
        "Iran",
        "Saudi Arabia",
        "UAE",
        "United Arab Emirates",
        "Qatar",
        "Bahrain",
        "Kuwait",
        "Oman",
        "Yemen",
        # Africa - North
        "Egypt",
        "Morocco",
        "Algeria",
        "Tunisia",
        "Libya",
        # Africa - West
        "Nigeria",
        "Ghana",
        "Senegal",
        "Ivory Coast",
        "Côte d'Ivoire",
        "Mali",
        "Burkina Faso",
        "Niger",
        "Benin",
        "Togo",
        "Gambia",
        "Guinea",
        "Sierra Leone",
        "Liberia",
        "Mauritania",
        "Cape Verde",
        # Africa - East
        "Kenya",
        "Tanzania",
        "Uganda",
        "Rwanda",
        "Burundi",
        "Ethiopia",
        "Eritrea",
        "Djibouti",
        "Somalia",
        "Sudan",
        "South Sudan",
        "Seychelles",
        "Mauritius",
        "Madagascar",
        "Comoros",
        "Mayotte",
        # Africa - Central
        "DRC",
        "Democratic Republic of Congo",
        "Congo",
        "Cameroon",
        "Central African Republic",
        "Chad",
        "Gabon",
        "Equatorial Guinea",
        "Sao Tome and Principe",
        # Africa - Southern
        "South Africa",
        "Namibia",
        "Botswana",
        "Zimbabwe",
        "Zambia",
        "Malawi",
        "Mozambique",
        "Angola",
        "Lesotho",
        "Eswatini",
        "Swaziland",
        # Asia - East
        "China",
        "Japan",
        "South Korea",
        "Korea",
        "North Korea",
        "Taiwan",
        "Mongolia",
        "Hong Kong",
        "Macau",
        "Macao",
        # Asia - Southeast
        "Thailand",
        "Vietnam",
        "Malaysia",
        "Singapore",
        "Indonesia",
        "Philippines",
        "Myanmar",
        "Burma",
        "Cambodia",
        "Laos",
        "Brunei",
        "East Timor",
        "Timor-Leste",
        # Asia - South
        "India",
        "Pakistan",
        "Bangladesh",
        "Sri Lanka",
        "Nepal",
        "Bhutan",
        "Maldives",
        "Afghanistan",
        # Asia - Central
        "Kazakhstan",
        "Uzbekistan",
        "Turkmenistan",
        "Kyrgyzstan",
        "Tajikistan",
        "Azerbaijan",
        "Georgia",
        "Armenia",
        # Oceania
        "Australia",
        "New Zealand",
        "Papua New Guinea",
        "Fiji",
        "Samoa",
        "Tonga",
        "Vanuatu",
        "Solomon Islands",
        "New Caledonia",
        "French Polynesia",
        "Guam",
        "Palau",
        "Micronesia",
        "Marshall Islands",
        "Kiribati",
        "Tuvalu",
        "Nauru",
        "Cook Islands",
    }
)

# Regions, landmarks, and non-standard destinations
KNOWN_REGIONS: FrozenSet[str] = frozenset(
    {
        # Famous regions
        "Patagonia",
        "Tuscany",
        "Provence",
        "Burgundy",
        "Champagne",
        "Alsace",
        "Normandy",
        "Brittany",
        "Loire Valley",
        "French Riviera",
        "Côte d'Azur",
        "Amalfi Coast",
        "Cinque Terre",
        "Dolomites",
        "Italian Riviera",
        "Costa Brava",
        "Costa del Sol",
        "Andalusia",
        "Andalucía",
        "Basque Country",
        "Galicia",
        "Catalonia",
        "Balearic Islands",
        "Canary Islands",
        "Algarve",
        "Douro Valley",
        "Madeira",
        "Azores",
        "Scottish Highlands",
        "Lake District",
        "Cotswolds",
        "Cornwall",
        "Black Forest",
        "Bavarian Alps",
        "Rhine Valley",
        "Romantic Road",
        "Swiss Alps",
        "Austrian Alps",
        "Tyrol",
        "Salzburgerland",
        "Dalmatian Coast",
        "Istria",
        "Transylvania",
        "Norwegian Fjords",
        "Lapland",
        "Finnish Lakeland",
        # Americas regions
        "Caribbean",
        "West Indies",
        "Central America",
        "South America",
        "Yucatan",
        "Yucatán",
        "Riviera Maya",
        "Baja California",
        "Copper Canyon",
        "Amazon",
        "Amazon Rainforest",
        "Galapagos",
        "Galápagos",
        "Machu Picchu",
        "Sacred Valley",
        "Inca Trail",
        "Atacama",
        "Atacama Desert",
        "Torres del Paine",
        "Iguazu",
        "Iguaçu",
        "Iguazu Falls",
        "Pantanal",
        "Fernando de Noronha",
        "Northeast Brazil",
        "Pacific Coast Highway",
        "Route 66",
        "Grand Canyon",
        "Yellowstone",
        "Yosemite",
        "Death Valley",
        "Joshua Tree",
        "Monument Valley",
        "Napa Valley",
        "Sonoma",
        "Big Sur",
        "Pacific Northwest",
        "New England",
        "Florida Keys",
        "Everglades",
        "Outer Banks",
        "Great Smoky Mountains",
        "Blue Ridge Parkway",
        "Appalachian Trail",
        "Rocky Mountains",
        "Rockies",
        "Alaska Inside Passage",
        "Denali",
        "Hawaii",
        "Hawaiian Islands",
        "Niagara Falls",
        "Canadian Rockies",
        "Banff",
        "Jasper",
        "Whistler",
        "Vancouver Island",
        "Bay of Fundy",
        "Prince Edward Island",
        "Maritimes",
        # Asia regions
        "Southeast Asia",
        "Indochina",
        "Mekong Delta",
        "Halong Bay",
        "Ha Long Bay",
        "Sapa",
        "Golden Triangle",
        "Northern Thailand",
        "Southern Thailand",
        "Thai Islands",
        "Borneo",
        "Raja Ampat",
        "Komodo",
        "Gili Islands",
        "Great Wall",
        "Silk Road",
        "Tibet",
        "Yunnan",
        "Zhangjiajie",
        "Hokkaido",
        "Mount Fuji",
        "Japanese Alps",
        "Okinawa Islands",
        "Korean DMZ",
        "Jeju Island",
        "Himalayas",
        "Kashmir",
        "Ladakh",
        "Rajasthan",
        "Kerala Backwaters",
        "Goa",
        "Andaman Islands",
        "Angkor",
        "Angkor Wat",
        "Temples of Angkor",
        # Middle East/Africa regions
        "Holy Land",
        "Petra",
        "Wadi Rum",
        "Dead Sea",
        "Red Sea",
        "Nile",
        "Nile Valley",
        "Valley of the Kings",
        "Sinai",
        "Sahara",
        "Sahara Desert",
        "Atlas Mountains",
        "High Atlas",
        "Serengeti",
        "Masai Mara",
        "Maasai Mara",
        "Kruger",
        "Kruger Park",
        "Okavango",
        "Okavango Delta",
        "Victoria Falls",
        "Garden Route",
        "Cape Winelands",
        "Wild Coast",
        "Skeleton Coast",
        "Namib Desert",
        "Mount Kilimanjaro",
        "Kilimanjaro",
        "Ngorongoro",
        "Ngorongoro Crater",
        # Oceania regions
        "Great Barrier Reef",
        "Whitsundays",
        "Gold Coast",
        "Sunshine Coast",
        "Outback",
        "Australian Outback",
        "Red Centre",
        "Uluru",
        "Ayers Rock",
        "Great Ocean Road",
        "Tasmania",
        "Blue Mountains",
        "Kimberley",
        "New Zealand South Island",
        "New Zealand North Island",
        "Milford Sound",
        "Fiordland",
        "Abel Tasman",
        "Bay of Islands",
        "Coromandel",
        "French Polynesia",
        "Society Islands",
        "Tuamotu",
        "Marquesas",
        # Europe - more regions
        "Alps",
        "Pyrenees",
        "Mediterranean",
        "Adriatic",
        "Aegean",
        "Baltic",
        "Scandinavian",
        "Nordic",
        "Balkans",
        "Eastern Europe",
        "Western Europe",
        # Islands and archipelagos
        "Maldives",
        "Seychelles",
        "Mauritius",
        "Reunion",
        "Réunion",
        "Zanzibar",
        "Lamu",
        "Cape Verde",
        "Canaries",
        "Balearics",
        "Mallorca",
        "Majorca",
        "Ibiza",
        "Menorca",
        "Formentera",
        "Greek Islands",
        "Cyclades",
        "Dodecanese",
        "Ionian Islands",
        "Sardinia",
        "Sicily",
        "Corsica",
        "Elba",
        "Channel Islands",
        "Jersey",
        "Guernsey",
        "Isle of Man",
        "Isle of Wight",
        "Faroe",
        "Faroe Islands",
        "Svalbard",
        "Lofoten",
        "Lofoten Islands",
        "Gotland",
        "Åland",
    }
)

# US States (for disambiguation)
US_STATES: FrozenSet[str] = frozenset(
    {
        "Alabama",
        "Alaska",
        "Arizona",
        "Arkansas",
        "California",
        "Colorado",
        "Connecticut",
        "Delaware",
        "Florida",
        "Georgia",
        "Hawaii",
        "Idaho",
        "Illinois",
        "Indiana",
        "Iowa",
        "Kansas",
        "Kentucky",
        "Louisiana",
        "Maine",
        "Maryland",
        "Massachusetts",
        "Michigan",
        "Minnesota",
        "Mississippi",
        "Missouri",
        "Montana",
        "Nebraska",
        "Nevada",
        "New Hampshire",
        "New Jersey",
        "New Mexico",
        "New York",
        "North Carolina",
        "North Dakota",
        "Ohio",
        "Oklahoma",
        "Oregon",
        "Pennsylvania",
        "Rhode Island",
        "South Carolina",
        "South Dakota",
        "Tennessee",
        "Texas",
        "Utah",
        "Vermont",
        "Virginia",
        "Washington",
        "West Virginia",
        "Wisconsin",
        "Wyoming",
        "District of Columbia",
        "DC",
    }
)

# All known places combined
ALL_KNOWN_PLACES: FrozenSet[str] = KNOWN_CITIES | KNOWN_COUNTRIES | KNOWN_REGIONS | US_STATES

# Lowercase version for case-insensitive lookups
_ALL_KNOWN_PLACES_LOWER: FrozenSet[str] = frozenset(p.lower() for p in ALL_KNOWN_PLACES)

# Mapping from lowercase to canonical form
_CANONICAL_PLACES: Dict[str, str] = {p.lower(): p for p in ALL_KNOWN_PLACES}

# =============================================================================
# PLACE SYNONYM NORMALIZATION
# =============================================================================
# Maps common abbreviations and alternate names to their canonical forms.
# This eliminates the need for LLM to handle synonym normalization.

PLACE_SYNONYMS: Dict[str, str] = {
    # US city abbreviations
    "nyc": "New York City",
    "new york city": "New York City",
    "la": "Los Angeles",
    "l.a.": "Los Angeles",
    "sf": "San Francisco",
    "s.f.": "San Francisco",
    "dc": "Washington, D.C.",
    "d.c.": "Washington, D.C.",
    "washington dc": "Washington, D.C.",
    "washington d.c.": "Washington, D.C.",
    "philly": "Philadelphia",
    "vegas": "Las Vegas",
    "nola": "New Orleans",
    "chi-town": "Chicago",
    "atl": "Atlanta",
    "bos": "Boston",
    "dtx": "Dallas",
    "dfw": "Dallas",
    # Country abbreviations
    "uk": "United Kingdom",
    "u.k.": "United Kingdom",
    "the uk": "United Kingdom",
    "britain": "United Kingdom",
    "great britain": "United Kingdom",
    "england": "United Kingdom",  # Often used interchangeably
    "usa": "United States",
    "u.s.a.": "United States",
    "u.s.": "United States",
    "the states": "United States",
    "america": "United States",
    "uae": "United Arab Emirates",
    "u.a.e.": "United Arab Emirates",
    "the emirates": "United Arab Emirates",
    # International city abbreviations
    "cdmx": "Mexico City",
    "df": "Mexico City",  # Distrito Federal
    "hk": "Hong Kong",
    "sg": "Singapore",
    "bkk": "Bangkok",
    "kl": "Kuala Lumpur",
    # Common alternate names
    "the big apple": "New York City",
    "city of lights": "Paris",
    "the city of light": "Paris",
    "the eternal city": "Rome",
    "the windy city": "Chicago",
    "sin city": "Las Vegas",
    "motor city": "Detroit",
    "mile high city": "Denver",
    "the crescent city": "New Orleans",
    "the bay area": "San Francisco Bay Area",
    "bay area": "San Francisco Bay Area",
    "silicon valley": "San Francisco Bay Area",
    "socal": "Southern California",
    "norcal": "Northern California",
    # European variants
    "munich": "Munich",  # vs München
    "cologne": "Cologne",  # vs Köln
    "vienna": "Vienna",  # vs Wien
    "prague": "Prague",  # vs Praha
    "warsaw": "Warsaw",  # vs Warszawa
    "moscow": "Moscow",  # vs Москва
    "rome": "Rome",  # vs Roma
    "milan": "Milan",  # vs Milano
    "florence": "Florence",  # vs Firenze
    "venice": "Venice",  # vs Venezia
    "naples": "Naples",  # vs Napoli
    "lisbon": "Lisbon",  # vs Lisboa
    "athens": "Athens",  # vs Αθήνα
    "copenhagen": "Copenhagen",  # vs København
    # Asian variants
    "beijing": "Beijing",  # vs Peking
    "peking": "Beijing",
    "bombay": "Mumbai",
    "calcutta": "Kolkata",
    "madras": "Chennai",
    "rangoon": "Yangon",
    "saigon": "Ho Chi Minh City",
    "canton": "Guangzhou",
    # Middle East
    "mecca": "Mecca",  # vs Makkah
    "makkah": "Mecca",
}

# Lowercase lookup for case-insensitive matching
_PLACE_SYNONYMS_LOWER: Dict[str, str] = {k.lower(): v for k, v in PLACE_SYNONYMS.items()}


def normalize_place_synonym(place: str) -> str:
    """
    Normalize a place name using the synonym map.

    Returns the canonical form if a synonym is found, otherwise the original.
    """
    if not place:
        return place
    lowered = place.lower().strip()
    return _PLACE_SYNONYMS_LOWER.get(lowered, place)


def normalize_places(places: List[str]) -> List[str]:
    """
    Normalize a list of place names, applying synonym mapping.

    Preserves order and removes duplicates after normalization.
    """
    if not places:
        return places

    seen: set[str] = set()
    result: List[str] = []
    for place in places:
        normalized = normalize_place_synonym(place)
        lower = normalized.lower()
        if lower not in seen:
            seen.add(lower)
            result.append(normalized)
    return result


# =============================================================================
# AMBIGUOUS ENTITIES
# =============================================================================

# Entities that could be places OR something else (person names, brands, etc.)
AMBIGUOUS_ENTITIES: Dict[str, Dict[str, any]] = {
    # Country/Person name ambiguity
    "jordan": {
        "types": ["country", "person_name"],
        "canonical": "Jordan",
        "ambiguity_penalty": 0.25,
    },
    "chad": {"types": ["country", "person_name"], "canonical": "Chad", "ambiguity_penalty": 0.25},
    "india": {"types": ["country", "person_name"], "canonical": "India", "ambiguity_penalty": 0.15},
    "china": {"types": ["country", "person_name"], "canonical": "China", "ambiguity_penalty": 0.15},
    "kenya": {"types": ["country", "person_name"], "canonical": "Kenya", "ambiguity_penalty": 0.20},
    "israel": {
        "types": ["country", "person_name"],
        "canonical": "Israel",
        "ambiguity_penalty": 0.15,
    },
    # Country/US State ambiguity
    "georgia": {
        "types": ["country", "us_state"],
        "canonical": "Georgia",
        "ambiguity_penalty": 0.30,
    },
    "washington": {
        "types": ["city", "us_state", "person_name"],
        "canonical": "Washington",
        "ambiguity_penalty": 0.25,
    },
    "new york": {"types": ["city", "us_state"], "canonical": "New York", "ambiguity_penalty": 0.10},
    # City/Common word ambiguity
    "nice": {"types": ["city", "adjective"], "canonical": "Nice", "ambiguity_penalty": 0.35},
    "reading": {"types": ["city", "verb"], "canonical": "Reading", "ambiguity_penalty": 0.30},
    "mobile": {"types": ["city", "adjective"], "canonical": "Mobile", "ambiguity_penalty": 0.30},
    "bath": {"types": ["city", "noun"], "canonical": "Bath", "ambiguity_penalty": 0.25},
    "split": {"types": ["city", "verb"], "canonical": "Split", "ambiguity_penalty": 0.30},
    "essen": {"types": ["city", "verb_german"], "canonical": "Essen", "ambiguity_penalty": 0.20},
    "bergen": {"types": ["city", "verb_german"], "canonical": "Bergen", "ambiguity_penalty": 0.15},
    # City/Person name ambiguity
    "paris": {"types": ["city", "person_name"], "canonical": "Paris", "ambiguity_penalty": 0.10},
    "sydney": {"types": ["city", "person_name"], "canonical": "Sydney", "ambiguity_penalty": 0.15},
    "austin": {"types": ["city", "person_name"], "canonical": "Austin", "ambiguity_penalty": 0.20},
    "houston": {
        "types": ["city", "person_name"],
        "canonical": "Houston",
        "ambiguity_penalty": 0.15,
    },
    "orlando": {
        "types": ["city", "person_name"],
        "canonical": "Orlando",
        "ambiguity_penalty": 0.15,
    },
    "jackson": {
        "types": ["city", "person_name"],
        "canonical": "Jackson",
        "ambiguity_penalty": 0.25,
    },
    "madison": {
        "types": ["city", "person_name"],
        "canonical": "Madison",
        "ambiguity_penalty": 0.20,
    },
    "charlotte": {
        "types": ["city", "person_name"],
        "canonical": "Charlotte",
        "ambiguity_penalty": 0.20,
    },
    "florence": {
        "types": ["city", "person_name"],
        "canonical": "Florence",
        "ambiguity_penalty": 0.15,
    },
    "victoria": {
        "types": ["city", "person_name"],
        "canonical": "Victoria",
        "ambiguity_penalty": 0.20,
    },
    "regina": {"types": ["city", "person_name"], "canonical": "Regina", "ambiguity_penalty": 0.25},
    "adelaide": {
        "types": ["city", "person_name"],
        "canonical": "Adelaide",
        "ambiguity_penalty": 0.20,
    },
    "alexandria": {
        "types": ["city", "person_name"],
        "canonical": "Alexandria",
        "ambiguity_penalty": 0.15,
    },
    "savannah": {
        "types": ["city", "person_name"],
        "canonical": "Savannah",
        "ambiguity_penalty": 0.20,
    },
    "brooklyn": {
        "types": ["city", "person_name"],
        "canonical": "Brooklyn",
        "ambiguity_penalty": 0.15,
    },
    "dakota": {
        "types": ["region", "person_name"],
        "canonical": "Dakota",
        "ambiguity_penalty": 0.25,
    },
    "montana": {
        "types": ["us_state", "person_name"],
        "canonical": "Montana",
        "ambiguity_penalty": 0.20,
    },
    "virginia": {
        "types": ["us_state", "person_name"],
        "canonical": "Virginia",
        "ambiguity_penalty": 0.15,
    },
    "carolina": {
        "types": ["region", "person_name"],
        "canonical": "Carolina",
        "ambiguity_penalty": 0.20,
    },
    # Brand/Place ambiguity
    "amazon": {"types": ["region", "company"], "canonical": "Amazon", "ambiguity_penalty": 0.30},
    "delta": {"types": ["region", "airline"], "canonical": "Delta", "ambiguity_penalty": 0.35},
    "united": {"types": ["airline", "adjective"], "canonical": "United", "ambiguity_penalty": 0.40},
    "virgin": {"types": ["brand", "adjective"], "canonical": "Virgin", "ambiguity_penalty": 0.35},
    "american": {
        "types": ["airline", "adjective"],
        "canonical": "American",
        "ambiguity_penalty": 0.40,
    },
    "frontier": {"types": ["airline", "noun"], "canonical": "Frontier", "ambiguity_penalty": 0.35},
}


# =============================================================================
# HELPER FUNCTIONS
# =============================================================================


def is_known_place(place: str) -> bool:
    """Check if a place name is in our known places database."""
    return place.lower() in _ALL_KNOWN_PLACES_LOWER


def get_canonical_place(place: str) -> Optional[str]:
    """Get the canonical form of a place name, or None if unknown."""
    return _CANONICAL_PLACES.get(place.lower())


def is_ambiguous_entity(entity: str) -> bool:
    """Check if an entity is known to be ambiguous."""
    return entity.lower() in AMBIGUOUS_ENTITIES


def get_ambiguity_info(entity: str) -> Optional[Dict]:
    """Get ambiguity information for an entity."""
    return AMBIGUOUS_ENTITIES.get(entity.lower())


def get_ambiguity_penalty(entity: str) -> float:
    """Get the confidence penalty for an ambiguous entity (0.0-1.0)."""
    info = AMBIGUOUS_ENTITIES.get(entity.lower())
    return info["ambiguity_penalty"] if info else 0.0
